// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.AzureIntegrationMigration.BizTalk.Analyze.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InformationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InformationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.AzureIntegrationMigration.BizTalk.Analyze.Resources.InformationMessages" +
                            "", typeof(InformationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The BizTalk File adapter property &apos;{0}&apos; with value &apos;{1}&apos; is not supported by the AIS File System connector..
        /// </summary>
        internal static string BizTalkFileAdapterPropertyNotSupported {
            get {
                return ResourceManager.GetString("BizTalkFileAdapterPropertyNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The BizTalk File adapter property &apos;{0}&apos; is not copied because it is a sensitive value and must be manually specified later in the generated template file where this property is used..
        /// </summary>
        internal static string BizTalkFileAdapterSensitivePropertyMustBeSpecifiedLater {
            get {
                return ResourceManager.GetString("BizTalkFileAdapterSensitivePropertyMustBeSpecifiedLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The BizTalk FTP adapter property &apos;{0}&apos; with value &apos;{1}&apos; is not supported by the AIS FTP connector..
        /// </summary>
        internal static string BizTalkFtpAdapterPropertyNotSupported {
            get {
                return ResourceManager.GetString("BizTalkFtpAdapterPropertyNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The BizTalk FTP adapter property &apos;{0}&apos; is not copied because it is a sensitive value and must be manually specified later in the generated template file where this property is used..
        /// </summary>
        internal static string BizTalkFtpAdapterSensitivePropertyMustBeSpecifiedLater {
            get {
                return ResourceManager.GetString("BizTalkFtpAdapterSensitivePropertyMustBeSpecifiedLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running BizTalk analyzer {AnalyzerName}..
        /// </summary>
        internal static string RunningBizTalkAnalyzer {
            get {
                return ResourceManager.GetString("RunningBizTalkAnalyzer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message declaration &apos;{0}&apos; depends on System object &apos;{1}&apos;..
        /// </summary>
        internal static string SystemSchemaDependencyFound {
            get {
                return ResourceManager.GetString("SystemSchemaDependencyFound", resourceCulture);
            }
        }
    }
}
