//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.AzureIntegrationMigration.BizTalk.Analyze.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MigrationTargetResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MigrationTargetResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.AzureIntegrationMigration.BizTalk.Analyze.Resources.MigrationTargetReso" +
                            "urces", typeof(MigrationTargetResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure Integration Application.
        /// </summary>
        internal static string ApplicationDescription {
            get {
                return ResourceManager.GetString("ApplicationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        internal static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BizTalk Framework assembler component..
        /// </summary>
        internal static string BizTalkFrameworkAssemblerDescription {
            get {
                return ResourceManager.GetString("BizTalkFrameworkAssemblerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BizTalk Framework assembler.
        /// </summary>
        internal static string BizTalkFrameworkAssemblerName {
            get {
                return ResourceManager.GetString("BizTalkFrameworkAssemblerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BizTalk Framework disassembler component..
        /// </summary>
        internal static string BizTalkFrameworkDisassemblerDescription {
            get {
                return ResourceManager.GetString("BizTalkFrameworkDisassemblerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BizTalk Framework disassembler.
        /// </summary>
        internal static string BizTalkFrameworkDisassemblerName {
            get {
                return ResourceManager.GetString("BizTalkFrameworkDisassemblerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The content based router decides which channel to route to based on the message content..
        /// </summary>
        internal static string ContentBasedRouterDescription {
            get {
                return ResourceManager.GetString("ContentBasedRouterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Based Router.
        /// </summary>
        internal static string ContentBasedRouterName {
            get {
                return ResourceManager.GetString("ContentBasedRouterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The content demoter demotes properties of the message bus envelope message into the output envelope or document business message..
        /// </summary>
        internal static string ContentDemoterDescription {
            get {
                return ResourceManager.GetString("ContentDemoterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Demoter.
        /// </summary>
        internal static string ContentDemoterName {
            get {
                return ResourceManager.GetString("ContentDemoterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The content promoter adds routing properties to the header of the message from routing property configuration..
        /// </summary>
        internal static string ContentPromoterDescription {
            get {
                return ResourceManager.GetString("ContentPromoterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Promoter.
        /// </summary>
        internal static string ContentPromoterName {
            get {
                return ResourceManager.GetString("ContentPromoterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DYNAMIC.
        /// </summary>
        internal static string DynamicSendPortDefaultProtocol {
            get {
                return ResourceManager.GetString("DynamicSendPortDefaultProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        internal static string EndRoute {
            get {
                return ResourceManager.GetString("EndRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flat file assembler component..
        /// </summary>
        internal static string FlatFileAssemblerDescription {
            get {
                return ResourceManager.GetString("FlatFileAssemblerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flat file assembler.
        /// </summary>
        internal static string FlatFileAssemblerName {
            get {
                return ResourceManager.GetString("FlatFileAssemblerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Streaming flat file disassembler component..
        /// </summary>
        internal static string FlatFileDisassemblerDescription {
            get {
                return ResourceManager.GetString("FlatFileDisassemblerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flat file disassembler.
        /// </summary>
        internal static string FlatFileDisassemblerName {
            get {
                return ResourceManager.GetString("FlatFileDisassemblerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The interchange aggregator collects all of the individual messages for an interchange to determine whether the interchange succeeded or failed as a single atomic unit..
        /// </summary>
        internal static string InterchangeAggregatorDescription {
            get {
                return ResourceManager.GetString("InterchangeAggregatorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interchange Aggregator.
        /// </summary>
        internal static string InterchangeAggregatorName {
            get {
                return ResourceManager.GetString("InterchangeAggregatorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The interchange queue is represented by a correlating queue channel..
        /// </summary>
        internal static string InterchangeQueueDescription {
            get {
                return ResourceManager.GetString("InterchangeQueueDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interchange Queue.
        /// </summary>
        internal static string InterchangeQueueName {
            get {
                return ResourceManager.GetString("InterchangeQueueName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The interchange splitter splits the successful interchange back into individual messages to be published to the message box topic..
        /// </summary>
        internal static string InterchangeSplitterDescription {
            get {
                return ResourceManager.GetString("InterchangeSplitterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interchange Splitter.
        /// </summary>
        internal static string InterchangeSplitterName {
            get {
                return ResourceManager.GetString("InterchangeSplitterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON decoder component..
        /// </summary>
        internal static string JsonDecoderDescription {
            get {
                return ResourceManager.GetString("JsonDecoderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON decoder.
        /// </summary>
        internal static string JsonDecoderName {
            get {
                return ResourceManager.GetString("JsonDecoderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON encoder component..
        /// </summary>
        internal static string JsonEncoderDescription {
            get {
                return ResourceManager.GetString("JsonEncoderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON encoder.
        /// </summary>
        internal static string JsonEncoderName {
            get {
                return ResourceManager.GetString("JsonEncoderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message box is represented by a publish-subscribe channel..
        /// </summary>
        internal static string MessageBoxDescription {
            get {
                return ResourceManager.GetString("MessageBoxDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Box.
        /// </summary>
        internal static string MessageBoxName {
            get {
                return ResourceManager.GetString("MessageBoxName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message box response is represented by a publish-subscribe channel..
        /// </summary>
        internal static string MessageBoxResponseDescription {
            get {
                return ResourceManager.GetString("MessageBoxResponseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Box Response.
        /// </summary>
        internal static string MessageBoxResponseName {
            get {
                return ResourceManager.GetString("MessageBoxResponseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message bus defines all of the core resources needed to support an enterprise application integration solution in Azure..
        /// </summary>
        internal static string MessageBusDescription {
            get {
                return ResourceManager.GetString("MessageBusDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Bus.
        /// </summary>
        internal static string MessageBusName {
            get {
                return ResourceManager.GetString("MessageBusName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message publisher sends the message to a publish-subscribe channel..
        /// </summary>
        internal static string MessagePublisherDescription {
            get {
                return ResourceManager.GetString("MessagePublisherDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Publisher.
        /// </summary>
        internal static string MessagePublisherName {
            get {
                return ResourceManager.GetString("MessagePublisherName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message subscriber receives a message from a publish-subscribe channel using a subscription filter..
        /// </summary>
        internal static string MessageSubscriberDescription {
            get {
                return ResourceManager.GetString("MessageSubscriberDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Subscriber.
        /// </summary>
        internal static string MessageSubscriberName {
            get {
                return ResourceManager.GetString("MessageSubscriberName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIME/SMIME decoder component..
        /// </summary>
        internal static string MimeDecoderDescription {
            get {
                return ResourceManager.GetString("MimeDecoderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIME/SMIME decoder.
        /// </summary>
        internal static string MimeDecoderName {
            get {
                return ResourceManager.GetString("MimeDecoderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIME/SMIME encoder component..
        /// </summary>
        internal static string MimeEncoderDescription {
            get {
                return ResourceManager.GetString("MimeEncoderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIME/SMIME encoder.
        /// </summary>
        internal static string MimeEncoderName {
            get {
                return ResourceManager.GetString("MimeEncoderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party resolution component..
        /// </summary>
        internal static string PartyResolverDescription {
            get {
                return ResourceManager.GetString("PartyResolverDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party resolution.
        /// </summary>
        internal static string PartyResolverName {
            get {
                return ResourceManager.GetString("PartyResolverName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RouteFrom.
        /// </summary>
        internal static string RouteFromChannelLabel {
            get {
                return ResourceManager.GetString("RouteFromChannelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RouteTo.
        /// </summary>
        internal static string RouteToChannelLabel {
            get {
                return ResourceManager.GetString("RouteToChannelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The routing slip router calls the next step in the route which is {0}..
        /// </summary>
        internal static string RoutingSlipRouterDescription {
            get {
                return ResourceManager.GetString("RoutingSlipRouterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Routing Slip Router.
        /// </summary>
        internal static string RoutingSlipRouterName {
            get {
                return ResourceManager.GetString("RoutingSlipRouterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure Integration Application Schema.
        /// </summary>
        internal static string SchemaDescription {
            get {
                return ResourceManager.GetString("SchemaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema.
        /// </summary>
        internal static string SchemaName {
            get {
                return ResourceManager.GetString("SchemaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The suspend queue is represented by a publish-subscribe channel..
        /// </summary>
        internal static string SuspendQueueDescription {
            get {
                return ResourceManager.GetString("SuspendQueueDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suspend Queue.
        /// </summary>
        internal static string SuspendQueueName {
            get {
                return ResourceManager.GetString("SuspendQueueName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure Integration System Application.
        /// </summary>
        internal static string SystemApplicationDescription {
            get {
                return ResourceManager.GetString("SystemApplicationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Application.
        /// </summary>
        internal static string SystemApplicationName {
            get {
                return ResourceManager.GetString("SystemApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The trigger channel sends a message to a URL endpoint which triggers the {0} intermediary..
        /// </summary>
        internal static string TriggerChannelDescription {
            get {
                return ResourceManager.GetString("TriggerChannelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigger Channel.
        /// </summary>
        internal static string TriggerChannelName {
            get {
                return ResourceManager.GetString("TriggerChannelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML assembler component..
        /// </summary>
        internal static string XmlAssemblerDescription {
            get {
                return ResourceManager.GetString("XmlAssemblerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML assembler.
        /// </summary>
        internal static string XmlAssemblerName {
            get {
                return ResourceManager.GetString("XmlAssemblerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Streaming XML disassembler..
        /// </summary>
        internal static string XmlDisassemblerDescription {
            get {
                return ResourceManager.GetString("XmlDisassemblerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML disassembler.
        /// </summary>
        internal static string XmlDisassemblerName {
            get {
                return ResourceManager.GetString("XmlDisassemblerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The XML message filter is used to filter XML messages that do not have a body or body data or have no associated schema..
        /// </summary>
        internal static string XmlMessageFilterDescription {
            get {
                return ResourceManager.GetString("XmlMessageFilterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML Message Filter.
        /// </summary>
        internal static string XmlMessageFilterName {
            get {
                return ResourceManager.GetString("XmlMessageFilterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The XML message translator uses a XSLT map to translate a received message into a new structure for output as a new message..
        /// </summary>
        internal static string XmlMessageTranslatorDescription {
            get {
                return ResourceManager.GetString("XmlMessageTranslatorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML Message Translator.
        /// </summary>
        internal static string XmlMessageTranslatorName {
            get {
                return ResourceManager.GetString("XmlMessageTranslatorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML validator component..
        /// </summary>
        internal static string XmlValidatorDescription {
            get {
                return ResourceManager.GetString("XmlValidatorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML validator.
        /// </summary>
        internal static string XmlValidatorName {
            get {
                return ResourceManager.GetString("XmlValidatorName", resourceCulture);
            }
        }
    }
}
