//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.AzureIntegrationMigration.BizTalk.Analyze.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TraceMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TraceMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.AzureIntegrationMigration.BizTalk.Analyze.Resources.TraceMessages", typeof(TraceMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Analyzing orchestration scenarios for application {ApplicationName} to create routes..
        /// </summary>
        internal static string AnalyzingOrchestrationScenarios {
            get {
                return ResourceManager.GetString("AnalyzingOrchestrationScenarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Analyzing receive port scenarios for application {ApplicationName} to create routes..
        /// </summary>
        internal static string AnalyzingReceivePortScenarios {
            get {
                return ResourceManager.GetString("AnalyzingReceivePortScenarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Analyzing dependencies for schema {name}..
        /// </summary>
        internal static string AnalyzingSchemaDependencies {
            get {
                return ResourceManager.GetString("AnalyzingSchemaDependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Analyzing send port scenarios for application {ApplicationName} to create routes..
        /// </summary>
        internal static string AnalyzingSendPortScenarios {
            get {
                return ResourceManager.GetString("AnalyzingSendPortScenarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Binding channels for receive port {ReceivePortName}..
        /// </summary>
        internal static string BindingChannelsForReceivePort {
            get {
                return ResourceManager.GetString("BindingChannelsForReceivePort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Binding channels for receive port response {ReceivePortName}..
        /// </summary>
        internal static string BindingChannelsForReceivePortResponse {
            get {
                return ResourceManager.GetString("BindingChannelsForReceivePortResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Binding channels for send port {SendPortName}..
        /// </summary>
        internal static string BindingChannelsForSendPort {
            get {
                return ResourceManager.GetString("BindingChannelsForSendPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Binding correlation variable {VariableName} for orchestration {OrchestrationName}..
        /// </summary>
        internal static string BindingCorrelationVariable {
            get {
                return ResourceManager.GetString("BindingCorrelationVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Binding invoked child workflow {InvokedWorkflowName} to the workflow {WorkflowName}..
        /// </summary>
        internal static string BindingInvokedWorkflow {
            get {
                return ResourceManager.GetString("BindingInvokedWorkflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Binding workflow channel {WorkflowChannelName} for invoke workflow activity {ActivityName}..
        /// </summary>
        internal static string BindingInvokeWorkflowActivity {
            get {
                return ResourceManager.GetString("BindingInvokeWorkflowActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Binding workflow channel {WorkflowChannelName} for receive activity {ActivityName}..
        /// </summary>
        internal static string BindingReceiveActivity {
            get {
                return ResourceManager.GetString("BindingReceiveActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Binding route with routing slip routers for receive port {ReceivePortName}..
        /// </summary>
        internal static string BindingRouteForReceivePort {
            get {
                return ResourceManager.GetString("BindingRouteForReceivePort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Binding route with routing slip routers for send port {SendPortName}..
        /// </summary>
        internal static string BindingRouteForSendPort {
            get {
                return ResourceManager.GetString("BindingRouteForSendPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Binding route with routing slip routers for response from send port {SendPortName}..
        /// </summary>
        internal static string BindingRouteForSendPortResponse {
            get {
                return ResourceManager.GetString("BindingRouteForSendPortResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Binding workflow channel {WorkflowChannelName} for send activity {ActivityName}..
        /// </summary>
        internal static string BindingSendActivity {
            get {
                return ResourceManager.GetString("BindingSendActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Binding workflow channel {WorkflowChannelName} for suspend activity {ActivityName}..
        /// </summary>
        internal static string BindingSuspendActivity {
            get {
                return ResourceManager.GetString("BindingSuspendActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Binding workflow channel {WorkflowChannelName} for terminate activity {ActivityName}..
        /// </summary>
        internal static string BindingTerminateActivity {
            get {
                return ResourceManager.GetString("BindingTerminateActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Binding workflow channels in model {WorkflowModelName} for orchestration {OrchestrationName} and activity container {ActivityContainerName}..
        /// </summary>
        internal static string BindingWorkflowChannels {
            get {
                return ResourceManager.GetString("BindingWorkflowChannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Binding workflow model for orchestration {OrchestrationName}..
        /// </summary>
        internal static string BindingWorkflowModel {
            get {
                return ResourceManager.GetString("BindingWorkflowModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: The BizTalk File receive adapter property {PropertyName} was found in the receive location {ReceiveLocationName}, using value {PropertyValue}..
        /// </summary>
        internal static string BizTalkFileReceiveAdapterBindingPropertyFound {
            get {
                return ResourceManager.GetString("BizTalkFileReceiveAdapterBindingPropertyFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: The BizTalk File receive adapter property {PropertyName} was not found in the receive location {ReceiveLocationName}, defaulting value to {PropertyDefaultValue}..
        /// </summary>
        internal static string BizTalkFileReceiveAdapterBindingPropertyNotFound {
            get {
                return ResourceManager.GetString("BizTalkFileReceiveAdapterBindingPropertyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: The BizTalk File receive adapter sensitive property {PropertyName} in the receive location {ReceiveLocationName} is being defaulted to an empty value..
        /// </summary>
        internal static string BizTalkFileReceiveAdapterBindingPropertySensitive {
            get {
                return ResourceManager.GetString("BizTalkFileReceiveAdapterBindingPropertySensitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: The BizTalk File send adapter property {PropertyName} was found in the send port {SendPortName}, using value {PropertyValue}..
        /// </summary>
        internal static string BizTalkFileSendAdapterBindingPropertyFound {
            get {
                return ResourceManager.GetString("BizTalkFileSendAdapterBindingPropertyFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: The BizTalk File send adapter sensitive property {PropertyName} in the send port {SendPortName} is being defaulted to an empty value..
        /// </summary>
        internal static string BizTalkFileSendAdapterBindingPropertySensitive {
            get {
                return ResourceManager.GetString("BizTalkFileSendAdapterBindingPropertySensitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: The BizTalk FTP receive adapter property {PropertyName} was found in the receive location {ReceiveLocationName}, using value {PropertyValue}..
        /// </summary>
        internal static string BizTalkFtpReceiveAdapterBindingPropertyFound {
            get {
                return ResourceManager.GetString("BizTalkFtpReceiveAdapterBindingPropertyFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: The BizTalk FTP receive adapter property {PropertyName} was not found in the receive location {ReceiveLocationName}, defaulting value to {PropertyDefaultValue}..
        /// </summary>
        internal static string BizTalkFtpReceiveAdapterBindingPropertyNotFound {
            get {
                return ResourceManager.GetString("BizTalkFtpReceiveAdapterBindingPropertyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: The BizTalk FTP receive adapter sensitive property {PropertyName} in the receive location {ReceiveLocationName} is being defaulted to an empty value..
        /// </summary>
        internal static string BizTalkFtpReceiveAdapterBindingPropertySensitive {
            get {
                return ResourceManager.GetString("BizTalkFtpReceiveAdapterBindingPropertySensitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: The BizTalk FTP send adapter property {PropertyName} was found in the send port {SendPortName}, using value {PropertyValue}..
        /// </summary>
        internal static string BizTalkFtpSendAdapterBindingPropertyFound {
            get {
                return ResourceManager.GetString("BizTalkFtpSendAdapterBindingPropertyFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: The BizTalk FTP send adapter property {PropertyName} was not found in the send port {SendPortName}, defaulting value to {PropertyDefaultValue}..
        /// </summary>
        internal static string BizTalkFtpSendAdapterBindingPropertyNotFound {
            get {
                return ResourceManager.GetString("BizTalkFtpSendAdapterBindingPropertyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: The BizTalk FTP send adapter sensitive property {PropertyName} in the send port {SendPortName} is being defaulted to an empty value..
        /// </summary>
        internal static string BizTalkFtpSendAdapterBindingPropertySensitive {
            get {
                return ResourceManager.GetString("BizTalkFtpSendAdapterBindingPropertySensitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: The BizTalk HTTP send adapter property {PropertyName} was found in the send port {SendPortName}, using value {PropertyValue}..
        /// </summary>
        internal static string BizTalkHttpSendAdapterBindingPropertyFound {
            get {
                return ResourceManager.GetString("BizTalkHttpSendAdapterBindingPropertyFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: The BizTalk HTTP send adapter property {PropertyName} was not found in the send port {SendPortName}, defaulting value to {PropertyDefaultValue}..
        /// </summary>
        internal static string BizTalkHttpSendAdapterBindingPropertyNotFound {
            get {
                return ResourceManager.GetString("BizTalkHttpSendAdapterBindingPropertyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: The BizTalk HTTP send adapter sensitive property {PropertyName} in the send port {SendPortName} is being defaulted to an empty value..
        /// </summary>
        internal static string BizTalkHttpSendAdapterBindingPropertySensitive {
            get {
                return ResourceManager.GetString("BizTalkHttpSendAdapterBindingPropertySensitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: The BizTalk MQ receive adapter property {PropertyName} was found in the receive location {ReceiveLocationName}, using value {PropertyValue}..
        /// </summary>
        internal static string BizTalkMqReceiveAdapterBindingPropertyFound {
            get {
                return ResourceManager.GetString("BizTalkMqReceiveAdapterBindingPropertyFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: The BizTalk MQ receive adapter property {PropertyName} was not found in the receive location {ReceiveLocationName}, defaulting value to {PropertyDefaultValue}..
        /// </summary>
        internal static string BizTalkMqReceiveAdapterBindingPropertyNotFound {
            get {
                return ResourceManager.GetString("BizTalkMqReceiveAdapterBindingPropertyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: The BizTalk MQ receive adapter sensitive property {PropertyName} in the receive location {ReceiveLocationName} is being defaulted to an empty value..
        /// </summary>
        internal static string BizTalkMqReceiveAdapterBindingPropertySensitive {
            get {
                return ResourceManager.GetString("BizTalkMqReceiveAdapterBindingPropertySensitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: The BizTalk MQ send adapter property {PropertyName} was found in the send port {SendPortName}, using value {PropertyValue}..
        /// </summary>
        internal static string BizTalkMqSendAdapterBindingPropertyFound {
            get {
                return ResourceManager.GetString("BizTalkMqSendAdapterBindingPropertyFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: The BizTalk MQ send adapter property {PropertyName} was not found in the send port {SendPortName}, defaulting value to {PropertyDefaultValue}..
        /// </summary>
        internal static string BizTalkMqSendAdapterBindingPropertyNotFound {
            get {
                return ResourceManager.GetString("BizTalkMqSendAdapterBindingPropertyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: The BizTalk MQ send adapter sensitive property {PropertyName} in the send port {SendPortName} is being defaulted to an empty value..
        /// </summary>
        internal static string BizTalkMqSendAdapterBindingPropertySensitive {
            get {
                return ResourceManager.GetString("BizTalkMqSendAdapterBindingPropertySensitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: The BizTalk SAP receive adapter property {PropertyName} was found in the receive location {ReceiveLocationName}, using value {PropertyValue}..
        /// </summary>
        internal static string BizTalkSapReceiveAdapterBindingPropertyFound {
            get {
                return ResourceManager.GetString("BizTalkSapReceiveAdapterBindingPropertyFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: The BizTalk SAP receive adapter property {PropertyName} was not found in the receive location {ReceiveLocationName}, defaulting value to {PropertyDefaultValue}..
        /// </summary>
        internal static string BizTalkSapReceiveAdapterBindingPropertyNotFound {
            get {
                return ResourceManager.GetString("BizTalkSapReceiveAdapterBindingPropertyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: The BizTalk SAP receive adapter sensitive property {PropertyName} in the receive location {ReceiveLocationName} is being defaulted to an empty value..
        /// </summary>
        internal static string BizTalkSapReceiveAdapterBindingPropertySensitive {
            get {
                return ResourceManager.GetString("BizTalkSapReceiveAdapterBindingPropertySensitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: The BizTalk SAP send adapter property {PropertyName} was found in the send port {SendPortName}, using value {PropertyValue}..
        /// </summary>
        internal static string BizTalkSapSendAdapterBindingPropertyFound {
            get {
                return ResourceManager.GetString("BizTalkSapSendAdapterBindingPropertyFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: The BizTalk SAP send adapter property {PropertyName} was not found in the send port {SendPortName}, defaulting value to {PropertyDefaultValue}..
        /// </summary>
        internal static string BizTalkSapSendAdapterBindingPropertyNotFound {
            get {
                return ResourceManager.GetString("BizTalkSapSendAdapterBindingPropertyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: The BizTalk SAP send adapter sensitive property {PropertyName} in the send port {SendPortName} is being defaulted to an empty value..
        /// </summary>
        internal static string BizTalkSapSendAdapterBindingPropertySensitive {
            get {
                return ResourceManager.GetString("BizTalkSapSendAdapterBindingPropertySensitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: The BizTalk SFTP receive adapter property {PropertyName} was found in the receive location {ReceiveLocationName}, using value {PropertyValue}..
        /// </summary>
        internal static string BizTalkSftpReceiveAdapterBindingPropertyFound {
            get {
                return ResourceManager.GetString("BizTalkSftpReceiveAdapterBindingPropertyFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: The BizTalk SFTP receive adapter property {PropertyName} was not found in the receive location {ReceiveLocationName}, defaulting value to {PropertyDefaultValue}..
        /// </summary>
        internal static string BizTalkSftpReceiveAdapterBindingPropertyNotFound {
            get {
                return ResourceManager.GetString("BizTalkSftpReceiveAdapterBindingPropertyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: The BizTalk SFTP receive adapter sensitive property {PropertyName} in the receive location {ReceiveLocationName} is being defaulted to an empty value..
        /// </summary>
        internal static string BizTalkSftpReceiveAdapterBindingPropertySensitive {
            get {
                return ResourceManager.GetString("BizTalkSftpReceiveAdapterBindingPropertySensitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: The BizTalk SFTP send adapter property {PropertyName} was found in the send port {SendPortName}, using value {PropertyValue}..
        /// </summary>
        internal static string BizTalkSftpSendAdapterBindingPropertyFound {
            get {
                return ResourceManager.GetString("BizTalkSftpSendAdapterBindingPropertyFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: The BizTalk SFTP send adapter property {PropertyName} was not found in the send port {SendPortName}, defaulting value to {PropertyDefaultValue}..
        /// </summary>
        internal static string BizTalkSftpSendAdapterBindingPropertyNotFound {
            get {
                return ResourceManager.GetString("BizTalkSftpSendAdapterBindingPropertyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: The BizTalk SFTP send adapter sensitive property {PropertyName} in the send port {SendPortName} is being defaulted to an empty value..
        /// </summary>
        internal static string BizTalkSftpSendAdapterBindingPropertySensitive {
            get {
                return ResourceManager.GetString("BizTalkSftpSendAdapterBindingPropertySensitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Channel {ChannelName} of type {ChannelType} in workflow {WorkflowName} has been bound to messaging channel {MessagingChannelName}..
        /// </summary>
        internal static string BoundWorkflowChannel {
            get {
                return ResourceManager.GetString("BoundWorkflowChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Building a new route to handle interchange batching..
        /// </summary>
        internal static string BuildingNewRouteForInterchangeBatching {
            get {
                return ResourceManager.GetString("BuildingNewRouteForInterchangeBatching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Building a new route to handle interchange batch completion..
        /// </summary>
        internal static string BuildingNewRouteForInterchangeHandling {
            get {
                return ResourceManager.GetString("BuildingNewRouteForInterchangeHandling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Building workflow model from metamodel for orchestration {OrchestrationName}..
        /// </summary>
        internal static string BuildingWorkflowModel {
            get {
                return ResourceManager.GetString("BuildingWorkflowModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Building route for process manager {IntermediaryName} in application {ApplicationName}..
        /// </summary>
        internal static string BuildingWorkflowRoute {
            get {
                return ResourceManager.GetString("BuildingWorkflowRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Checking for default pipeline..
        /// </summary>
        internal static string CheckingForDefaultPipeline {
            get {
                return ResourceManager.GetString("CheckingForDefaultPipeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Correlation variable {VariableName} is not bound to any receive or send activity, ignoring..
        /// </summary>
        internal static string CorrelationVariableNotBound {
            get {
                return ResourceManager.GetString("CorrelationVariableNotBound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Created subscription filter {PredicateGroup} group for send port {SendPortName} for the default subscription..
        /// </summary>
        internal static string CreatedDefaultSubscriptionFilterGroupForSendPort {
            get {
                return ResourceManager.GetString("CreatedDefaultSubscriptionFilterGroupForSendPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Created document message for schema {SchemaName}..
        /// </summary>
        internal static string CreatedDocumentMessage {
            get {
                return ResourceManager.GetString("CreatedDocumentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Created envelope message for schema {SchemaName}..
        /// </summary>
        internal static string CreatedEnvelopeMessage {
            get {
                return ResourceManager.GetString("CreatedEnvelopeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Created a workflow channel {ChannelName} of type {ChannelType} in invoked workflow {InvokedWorkflowName}..
        /// </summary>
        internal static string CreatedInvokedWorkflowChannel {
            get {
                return ResourceManager.GetString("CreatedInvokedWorkflowChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Created subscription filter {PredicateGroup} group for receive port {ReceivePortName} for all filter statement sub-groups..
        /// </summary>
        internal static string CreatedSubscriptionFilterGroupForReceivePort {
            get {
                return ResourceManager.GetString("CreatedSubscriptionFilterGroupForReceivePort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Created subscription filter {PredicateGroup} group for send port {SendPortName} for all filter statement sub-groups..
        /// </summary>
        internal static string CreatedSubscriptionFilterGroupForSendPort {
            get {
                return ResourceManager.GetString("CreatedSubscriptionFilterGroupForSendPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Created subscription filter statement {Statement}..
        /// </summary>
        internal static string CreatedSubscriptionFilterStatement {
            get {
                return ResourceManager.GetString("CreatedSubscriptionFilterStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Created subscription filter {PredicateGroup} group for {FilterStatementCount} filter statements..
        /// </summary>
        internal static string CreatedSubscriptionFilterSubGroup {
            get {
                return ResourceManager.GetString("CreatedSubscriptionFilterSubGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Created a workflow channel {ChannelName} of type {ChannelType}..
        /// </summary>
        internal static string CreatedWorkflowChannel {
            get {
                return ResourceManager.GetString("CreatedWorkflowChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Created a workflow composite message {MessageName} of type {MessageType}..
        /// </summary>
        internal static string CreatedWorkflowCompositeMessage {
            get {
                return ResourceManager.GetString("CreatedWorkflowCompositeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Created a workflow message part {PartName} of type {PartType}..
        /// </summary>
        internal static string CreatedWorkflowCompositeMessagePart {
            get {
                return ResourceManager.GetString("CreatedWorkflowCompositeMessagePart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Created a workflow correlation variable {VariableName} of type {VariableType}..
        /// </summary>
        internal static string CreatedWorkflowCorrelationVariable {
            get {
                return ResourceManager.GetString("CreatedWorkflowCorrelationVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Created a workflow message {MessageName} of type {MessageType}..
        /// </summary>
        internal static string CreatedWorkflowMessage {
            get {
                return ResourceManager.GetString("CreatedWorkflowMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Created a workflow variable {VariableName} of type {VariableType}..
        /// </summary>
        internal static string CreatedWorkflowVariable {
            get {
                return ResourceManager.GetString("CreatedWorkflowVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Creating content based router intermediary {IntermediaryName}..
        /// </summary>
        internal static string CreatingContentBasedRouterIntermediary {
            get {
                return ResourceManager.GetString("CreatingContentBasedRouterIntermediary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Creating content demoter intermediary {IntermediaryName}..
        /// </summary>
        internal static string CreatingContentDemoterIntermediary {
            get {
                return ResourceManager.GetString("CreatingContentDemoterIntermediary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Creating content promoter intermediary {IntermediaryName}..
        /// </summary>
        internal static string CreatingContentPromoterIntermediary {
            get {
                return ResourceManager.GetString("CreatingContentPromoterIntermediary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Creating intermediaries for the default pipeline {PipelineName}..
        /// </summary>
        internal static string CreatingDefaultPipelineComponentIntermediaries {
            get {
                return ResourceManager.GetString("CreatingDefaultPipelineComponentIntermediaries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Creating default subscription for send port {SendPortName}..
        /// </summary>
        internal static string CreatingDefaultSendPortSubscription {
            get {
                return ResourceManager.GetString("CreatingDefaultSendPortSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Creating an endpoint adapter for dynamic send port {SendPortName}..
        /// </summary>
        internal static string CreatingDynamicSendEndpointAdapter {
            get {
                return ResourceManager.GetString("CreatingDynamicSendEndpointAdapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Creating interchange aggregator intermediary {IntermediaryName}..
        /// </summary>
        internal static string CreatingInterchangeAggregatorIntermediary {
            get {
                return ResourceManager.GetString("CreatingInterchangeAggregatorIntermediary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Creating interchange splitter intermediary {IntermediaryName}..
        /// </summary>
        internal static string CreatingInterchangeSplitterIntermediary {
            get {
                return ResourceManager.GetString("CreatingInterchangeSplitterIntermediary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Creating JSON decoder intermediary {IntermediaryName}..
        /// </summary>
        internal static string CreatingJsonDecoderIntermediary {
            get {
                return ResourceManager.GetString("CreatingJsonDecoderIntermediary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Creating JSON encoder intermediary {IntermediaryName}..
        /// </summary>
        internal static string CreatingJsonEncoderIntermediary {
            get {
                return ResourceManager.GetString("CreatingJsonEncoderIntermediary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Creating message translator intermediary containing {MapCount} maps..
        /// </summary>
        internal static string CreatingMapIntermediary {
            get {
                return ResourceManager.GetString("CreatingMapIntermediary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Creating message publisher intermediary {IntermediaryName}..
        /// </summary>
        internal static string CreatingMessagePublisherIntermediary {
            get {
                return ResourceManager.GetString("CreatingMessagePublisherIntermediary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Creating message subscriber intermediary {IntermediaryName} for send port {SendPortName}..
        /// </summary>
        internal static string CreatingMessageSubscriberIntermediary {
            get {
                return ResourceManager.GetString("CreatingMessageSubscriberIntermediary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Creating message subscriber intermediary {IntermediaryName} for receive port {ReceivePortName}..
        /// </summary>
        internal static string CreatingMessageSubscriberIntermediaryReceivePort {
            get {
                return ResourceManager.GetString("CreatingMessageSubscriberIntermediaryReceivePort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Creating intermediaries for pipeline {PipelineName}..
        /// </summary>
        internal static string CreatingPipelineComponentIntermediaries {
            get {
                return ResourceManager.GetString("CreatingPipelineComponentIntermediaries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Creating an intermediary for pipeline component {ComponentName} for pipeline {PipelineName}..
        /// </summary>
        internal static string CreatingPipelineComponentIntermediary {
            get {
                return ResourceManager.GetString("CreatingPipelineComponentIntermediary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Creating queue channel {ChannelName}..
        /// </summary>
        internal static string CreatingQueueChannel {
            get {
                return ResourceManager.GetString("CreatingQueueChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Creating an endpoint adapter for protocol {ProtocolName} for receive location {ReceiveLocationName}..
        /// </summary>
        internal static string CreatingReceiveEndpointAdapter {
            get {
                return ResourceManager.GetString("CreatingReceiveEndpointAdapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Creating subscription for response path of receive port {ReceivePortName}..
        /// </summary>
        internal static string CreatingReceivePortResponseSubscription {
            get {
                return ResourceManager.GetString("CreatingReceivePortResponseSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Creating subscription for receive port {ReceivePortName}..
        /// </summary>
        internal static string CreatingReceivePortSubscription {
            get {
                return ResourceManager.GetString("CreatingReceivePortSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Creating routing slip router intermediary from step {FromStep} to step {ToStep}..
        /// </summary>
        internal static string CreatingRoutingSlipRouterIntermediary {
            get {
                return ResourceManager.GetString("CreatingRoutingSlipRouterIntermediary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Creating an endpoint adapter for protocol {ProtocolName} for send port {SendPortName}..
        /// </summary>
        internal static string CreatingSendEndpointAdapter {
            get {
                return ResourceManager.GetString("CreatingSendEndpointAdapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Creating subscription for send port {SendPortName}..
        /// </summary>
        internal static string CreatingSendPortSubscription {
            get {
                return ResourceManager.GetString("CreatingSendPortSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Creating topic channel {ChannelName}..
        /// </summary>
        internal static string CreatingTopicChannel {
            get {
                return ResourceManager.GetString("CreatingTopicChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Creating XML envelope wrapper intermediary {IntermediaryName}..
        /// </summary>
        internal static string CreatingXmlEnvelopeWrapperIntermediary {
            get {
                return ResourceManager.GetString("CreatingXmlEnvelopeWrapperIntermediary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Creating XML message filter intermediary {IntermediaryName}..
        /// </summary>
        internal static string CreatingXmlMessageFilterIntermediary {
            get {
                return ResourceManager.GetString("CreatingXmlMessageFilterIntermediary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Creating XML message processor intermediary {IntermediaryName}..
        /// </summary>
        internal static string CreatingXmlMessageProcessorIntermediary {
            get {
                return ResourceManager.GetString("CreatingXmlMessageProcessorIntermediary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Creating XML message validator intermediary {IntermediaryName}..
        /// </summary>
        internal static string CreatingXmlMessageValidatorIntermediary {
            get {
                return ResourceManager.GetString("CreatingXmlMessageValidatorIntermediary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Found {ScenarioCount} orchestration scenarios for application {ApplicationName}..
        /// </summary>
        internal static string FoundOrchestrationScenariosInApplication {
            get {
                return ResourceManager.GetString("FoundOrchestrationScenariosInApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Found {PipelineComponentCount} pipeline components in pipeline {PipelineName}..
        /// </summary>
        internal static string FoundPipelineComponentsInPipeline {
            get {
                return ResourceManager.GetString("FoundPipelineComponentsInPipeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Found messaging port {PortName} in bindings for channel {ChannelName} bound to receive activity {ReceiveActivityName} in workflow {WorkflowName}..
        /// </summary>
        internal static string FoundPortForReceiveActivityLogicalBinding {
            get {
                return ResourceManager.GetString("FoundPortForReceiveActivityLogicalBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Found messaging port {PortName} in bindings for channel {ChannelName} bound to send activity {SendActivityName} in workflow {WorkflowName}..
        /// </summary>
        internal static string FoundPortForSendActivityLogicalBinding {
            get {
                return ResourceManager.GetString("FoundPortForSendActivityLogicalBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Found {ScenarioCount} receive port scenarios for application {ApplicationName}..
        /// </summary>
        internal static string FoundReceivePortScenariosInApplication {
            get {
                return ResourceManager.GetString("FoundReceivePortScenariosInApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Found {ScenarioCount} send port scenarios for application {ApplicationName}..
        /// </summary>
        internal static string FoundSendPortScenariosInApplication {
            get {
                return ResourceManager.GetString("FoundSendPortScenariosInApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating resources from configuration in target model..
        /// </summary>
        internal static string GeneratingResourcesInTargetModel {
            get {
                return ResourceManager.GetString("GeneratingResourcesInTargetModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Transform {TransformName} not used by any receive ports..
        /// </summary>
        internal static string MapNotUsedByReceivePorts {
            get {
                return ResourceManager.GetString("MapNotUsedByReceivePorts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Transform {TransformName} not used by any send ports..
        /// </summary>
        internal static string MapNotUsedBySendPorts {
            get {
                return ResourceManager.GetString("MapNotUsedBySendPorts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Mapped subscription filter property {FilterPropertyName} to {MappedFilterPropertyName}..
        /// </summary>
        internal static string MappedSubscriptionFilterPropertyName {
            get {
                return ResourceManager.GetString("MappedSubscriptionFilterPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created migration source report Ref &apos;{RefId}&apos;..
        /// </summary>
        internal static string MigrationSourceCreated {
            get {
                return ResourceManager.GetString("MigrationSourceCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: No activatable process managers found in the application {ApplicationName}..
        /// </summary>
        internal static string NoActivatableProcessManagersInApplication {
            get {
                return ResourceManager.GetString("NoActivatableProcessManagersInApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: No orchestrations found for application {ApplicationName}..
        /// </summary>
        internal static string NoOrchestrationsFoundInApplication {
            get {
                return ResourceManager.GetString("NoOrchestrationsFoundInApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: No map specified on receive port {ReceivePortName}, skipping for receive location {ReceiveLocationName}..
        /// </summary>
        internal static string NoReceiveMapSpecifiedOnReceivePort {
            get {
                return ResourceManager.GetString("NoReceiveMapSpecifiedOnReceivePort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: No map specified on send port {SendPortName}, skipping..
        /// </summary>
        internal static string NoReceiveMapSpecifiedOnSendPort {
            get {
                return ResourceManager.GetString("NoReceiveMapSpecifiedOnSendPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: No receive ports found for application {ApplicationName}..
        /// </summary>
        internal static string NoReceivePortsFoundInApplication {
            get {
                return ResourceManager.GetString("NoReceivePortsFoundInApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: No map specified on send port {SendPortName}, skipping..
        /// </summary>
        internal static string NoSendMapSpecifiedOnSendPort {
            get {
                return ResourceManager.GetString("NoSendMapSpecifiedOnSendPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: No send ports found for application {ApplicationName}..
        /// </summary>
        internal static string NoSendPortsFoundInApplication {
            get {
                return ResourceManager.GetString("NoSendPortsFoundInApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: The {PipelineName} does not require intermediaries..
        /// </summary>
        internal static string PassthruPipelineDoesNotRequireIntermediaries {
            get {
                return ResourceManager.GetString("PassthruPipelineDoesNotRequireIntermediaries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: The pipeline component {PipelineComponentName} is not recognised as a default component, creating a custom filter intermediary for the custom component..
        /// </summary>
        internal static string PipelineComponentNotRecognisedAsDefaultComponent {
            get {
                return ResourceManager.GetString("PipelineComponentNotRecognisedAsDefaultComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Route for process manager {ProcessManagerName} has been bound with {MessagingObjectCount} messaging objects in the route..
        /// </summary>
        internal static string ProcessManagerRouteBound {
            get {
                return ResourceManager.GetString("ProcessManagerRouteBound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Receive port {ReceivePort} is two way, analyzing response path..
        /// </summary>
        internal static string ReceivePortIsTwoWay {
            get {
                return ResourceManager.GetString("ReceivePortIsTwoWay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Created relationship from resource &apos;{0}&apos; to resource &apos;{1}&apos; using relationship &apos;{2}&apos;..
        /// </summary>
        internal static string RelationshipCreated {
            get {
                return ResourceManager.GetString("RelationshipCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rendering template configuration in temp path {TempPath}..
        /// </summary>
        internal static string RenderingTemplateConfigInTempPath {
            get {
                return ResourceManager.GetString("RenderingTemplateConfigInTempPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created report resource container &apos;{RefId}&apos; Key &apos;{Key}&apos; Name &apos;{Name}&apos; Type &apos;{Type}&apos; in the container &apos;{ParentRefId}&apos;..
        /// </summary>
        internal static string ReportContainerCreated {
            get {
                return ResourceManager.GetString("ReportContainerCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Created resource &apos;{RefId}&apos; Name &apos;{Name}&apos; Type &apos;{Type}&apos; in the resource &apos;{ParentRefId}&apos;..
        /// </summary>
        internal static string ReportResourceCreated {
            get {
                return ResourceManager.GetString("ReportResourceCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Resolving receive and send ports for transform {TransformName}..
        /// </summary>
        internal static string ResolvingPortsForMap {
            get {
                return ResourceManager.GetString("ResolvingPortsForMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Resolving source schemas for transform {TransformName}..
        /// </summary>
        internal static string ResolvingSourceSchemasForMap {
            get {
                return ResourceManager.GetString("ResolvingSourceSchemasForMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Resolving target schemas for transform {TransformName}..
        /// </summary>
        internal static string ResolvingTargetSchemasForMap {
            get {
                return ResourceManager.GetString("ResolvingTargetSchemasForMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created resource &apos;{RefId}&apos; Key &apos;{Key}&apos; Name &apos;{Name}&apos; Type &apos;{Type}&apos; in the resource &apos;{ParentKey}&apos; Type &apos;{ParentType}&apos;..
        /// </summary>
        internal static string ResourceCreated {
            get {
                return ResourceManager.GetString("ResourceCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created resource definition &apos;{RefId}&apos; Key &apos;{Key}&apos; Name &apos;{Name}&apos; Type &apos;{Type}&apos; in the container &apos;{ContainerKey}&apos; Type &apos;{ContainerType}&apos;..
        /// </summary>
        internal static string ResourceDefinitionCreated {
            get {
                return ResourceManager.GetString("ResourceDefinitionCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving rendered template configuration from {TempPath}..
        /// </summary>
        internal static string RetrievingConfigurationFromTempPath {
            get {
                return ResourceManager.GetString("RetrievingConfigurationFromTempPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Completed running rule {RuleName}..
        /// </summary>
        internal static string RuleCompleted {
            get {
                return ResourceManager.GetString("RuleCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running BizTalk analyzer {AnalyzerName}..
        /// </summary>
        internal static string RunningBizTalkAnalyzer {
            get {
                return ResourceManager.GetString("RunningBizTalkAnalyzer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running initializer {InitializorName}..
        /// </summary>
        internal static string RunningInitializerAnalyzer {
            get {
                return ResourceManager.GetString("RunningInitializerAnalyzer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Running rule {RuleName}..
        /// </summary>
        internal static string RunningRule {
            get {
                return ResourceManager.GetString("RunningRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Schema dependency has not been resolved for schema {SchemaType}..
        /// </summary>
        internal static string SchemaDependencyNotResolved {
            get {
                return ResourceManager.GetString("SchemaDependencyNotResolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Send port {SendPort} is two way, analyzing response path..
        /// </summary>
        internal static string SendPortIsTwoWay {
            get {
                return ResourceManager.GetString("SendPortIsTwoWay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Skipping the rule {RuleName} as there is no source model..
        /// </summary>
        internal static string SkippingRuleAsSourceModelMissing {
            get {
                return ResourceManager.GetString("SkippingRuleAsSourceModelMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Transform dependency has not been resolved for schema {TransformType}..
        /// </summary>
        internal static string TransformDependencyNotResolved {
            get {
                return ResourceManager.GetString("TransformDependencyNotResolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Using default property value {PropertyValue} for {PropertyName} in pipeline component {ComponentName}..
        /// </summary>
        internal static string UsingDefaultPropertyValueForPipelineComponent {
            get {
                return ResourceManager.GetString("UsingDefaultPropertyValueForPipelineComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Using overridden property value {PropertyValue} for {PropertyName} in pipeline component {ComponentName}..
        /// </summary>
        internal static string UsingOverriddenPropertyValueForPipelineComponent {
            get {
                return ResourceManager.GetString("UsingOverriddenPropertyValueForPipelineComponent", resourceCulture);
            }
        }
    }
}
