//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.AzureIntegrationMigration.BizTalk.Analyze.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WarningMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WarningMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.AzureIntegrationMigration.BizTalk.Analyze.Resources.WarningMessages", typeof(WarningMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application &apos;{0}&apos; referenced by application &apos;{1}&apos; is missing in the parsed BizTalk application..
        /// </summary>
        internal static string ApplicationReferencedByApplicationIsMissing {
            get {
                return ResourceManager.GetString("ApplicationReferencedByApplicationIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The context property &apos;{0}&apos; referenced by schema &apos;{1}&apos; is missing in the parsed BizTalk application..
        /// </summary>
        internal static string ContextPropertyReferencedBySchemaIsMissing {
            get {
                return ResourceManager.GetString("ContextPropertyReferencedBySchemaIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There were multiple matches for Send Port &apos;{0}&apos; referenced by Distribution List &apos;{1}&apos; with key &apos;{2}&apos;.   Dependency cannot be accurately resolved..
        /// </summary>
        internal static string DistributionListSendPortMultipleMatches {
            get {
                return ResourceManager.GetString("DistributionListSendPortMultipleMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Send Port &apos;{0}&apos; referenced by Distribution List &apos;{1}&apos; with key &apos;{2}&apos; could not be located..
        /// </summary>
        internal static string DistributionListSendPortNotFound {
            get {
                return ResourceManager.GetString("DistributionListSendPortNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The TransportTypeData for ReceiveLocation {0} was empty..
        /// </summary>
        internal static string ReceiveLocationTransportTypeDataNotFound {
            get {
                return ResourceManager.GetString("ReceiveLocationTransportTypeDataNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The schema &apos;{0}&apos; referenced by the message declaration &apos;{1}&apos; is missing in the parsed BizTalk application..
        /// </summary>
        internal static string SchemaReferencedByMessageDeclarationIsMissing {
            get {
                return ResourceManager.GetString("SchemaReferencedByMessageDeclarationIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The schema &apos;{0}&apos; referenced by pipeline component &apos;{1}&apos; is missing in the parsed BizTalk application..
        /// </summary>
        internal static string SchemaReferencedByPipelineComponentIsMissing {
            get {
                return ResourceManager.GetString("SchemaReferencedByPipelineComponentIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The schema &apos;{0}&apos; referenced by transform &apos;{1}&apos; is missing in the parsed BizTalk application..
        /// </summary>
        internal static string SchemaReferencedByTransformIsMissing {
            get {
                return ResourceManager.GetString("SchemaReferencedByTransformIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The schema &apos;{0}&apos; referenced by message declaration &apos;{1}&apos; has &apos;{2}&apos; matches.  Dependency cannot be accurately resolved..
        /// </summary>
        internal static string SchemaReferenceMultipleMatches {
            get {
                return ResourceManager.GetString("SchemaReferenceMultipleMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The TransportTypeData for SendPort {0} was empty..
        /// </summary>
        internal static string SendPortTransportTypeDataNotFound {
            get {
                return ResourceManager.GetString("SendPortTransportTypeDataNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The pipeline {PipelineName} is not known by the analyzer and will be skipped..
        /// </summary>
        internal static string SkippingUnknownDefaultPipeline {
            get {
                return ResourceManager.GetString("SkippingUnknownDefaultPipeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The transform &apos;{0}&apos; referenced by the service declaration &apos;{1}&apos; is missing in the parsed BizTalk application..
        /// </summary>
        internal static string TransformReferencedByServiceDeclarationIsMissing {
            get {
                return ResourceManager.GetString("TransformReferencedByServiceDeclarationIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The transform (map) &apos;{0}&apos; referenced by service declaration &apos;{1}&apos; has &apos;{2}&apos; matches.  Dependency cannot be accurately resolved..
        /// </summary>
        internal static string TransformReferenceMultipleMatches {
            get {
                return ResourceManager.GetString("TransformReferenceMultipleMatches", resourceCulture);
            }
        }
    }
}
