// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.AzureIntegrationMigration.BizTalk.Discover.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TraceMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TraceMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.AzureIntegrationMigration.BizTalk.Discover.Resources.TraceMessages", typeof(TraceMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bootstrapped the working folder in the directory: {WorkingFolder}..
        /// </summary>
        internal static string BootstrappedWorkingFolder {
            get {
                return ResourceManager.GetString("BootstrappedWorkingFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bootstrapping the working folder in the directory: {WorkingDirectory}..
        /// </summary>
        internal static string BootstrappingWorkingFolderInDirectory {
            get {
                return ResourceManager.GetString("BootstrappingWorkingFolderInDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created the application resource definition: {ResourceDefinitionKey}..
        /// </summary>
        internal static string CreatedTheApplicationResourceDefinition {
            get {
                return ResourceManager.GetString("CreatedTheApplicationResourceDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created the resource definition: {ResourceDefinitionKey}..
        /// </summary>
        internal static string CreatedTheResourceDefinition {
            get {
                return ResourceManager.GetString("CreatedTheResourceDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discovered the assembly: {ContainerKey}..
        /// </summary>
        internal static string DiscoveredTheAssembly {
            get {
                return ResourceManager.GetString("DiscoveredTheAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discovered the binding file: {ResourceKey}..
        /// </summary>
        internal static string DiscoveredTheBindingFile {
            get {
                return ResourceManager.GetString("DiscoveredTheBindingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discovered the distinguished field: {XPath}..
        /// </summary>
        internal static string DiscoveredTheDistinguisedField {
            get {
                return ResourceManager.GetString("DiscoveredTheDistinguisedField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discovered the nested schema: {SchemaFullName}..
        /// </summary>
        internal static string DiscoveredTheNestedSchema {
            get {
                return ResourceManager.GetString("DiscoveredTheNestedSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discovered the orchestration: {ResourceKey}..
        /// </summary>
        internal static string DiscoveredTheOrchestration {
            get {
                return ResourceManager.GetString("DiscoveredTheOrchestration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discovered the promoted property: {XPath}..
        /// </summary>
        internal static string DiscoveredThePromotedProperty {
            get {
                return ResourceManager.GetString("DiscoveredThePromotedProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discovered the receive pipeline: {ResourceKey}..
        /// </summary>
        internal static string DiscoveredTheReceivePipeline {
            get {
                return ResourceManager.GetString("DiscoveredTheReceivePipeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discovered the schema: {SchemaFullName}..
        /// </summary>
        internal static string DiscoveredTheSchema {
            get {
                return ResourceManager.GetString("DiscoveredTheSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discovered the send pipeline: {ResourceKey}..
        /// </summary>
        internal static string DiscoveredTheSendPipeline {
            get {
                return ResourceManager.GetString("DiscoveredTheSendPipeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discovered the transform: {ResourceKey};.
        /// </summary>
        internal static string DiscoveredTheTransform {
            get {
                return ResourceManager.GetString("DiscoveredTheTransform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discovering the assembly contents in: {ResourceContainerKey}..
        /// </summary>
        internal static string DiscoveringAssemblyContentsInResourceContainer {
            get {
                return ResourceManager.GetString("DiscoveringAssemblyContentsInResourceContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discovering the resources in assembly container: {ContainerKey}..
        /// </summary>
        internal static string DiscoveringTheResourcesInAssemblyCointainer {
            get {
                return ResourceManager.GetString("DiscoveringTheResourcesInAssemblyCointainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discovering the schemas in the resource container: {CointainerKey}..
        /// </summary>
        internal static string DiscoveringTheSchemasInResourceContainer {
            get {
                return ResourceManager.GetString("DiscoveringTheSchemasInResourceContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracting the cabinet files in: {CabPath}..
        /// </summary>
        internal static string ExtractingCabFilesFromPath {
            get {
                return ResourceManager.GetString("ExtractingCabFilesFromPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipping the discovery in {DiscovererName} as there is no source model..
        /// </summary>
        internal static string SkippingDiscoveryAsTheSourceModelIsMissing {
            get {
                return ResourceManager.GetString("SkippingDiscoveryAsTheSourceModelIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpacking the MSI: {ContainerLocation}..
        /// </summary>
        internal static string UnpackingTheMsi {
            get {
                return ResourceManager.GetString("UnpackingTheMsi", resourceCulture);
            }
        }
    }
}
