// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.AzureIntegrationMigration.BizTalk.Convert.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.AzureIntegrationMigration.BizTalk.Convert.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The process manager &apos;{0}&apos; does not have an associated workflow model..
        /// </summary>
        internal static string ProcessManagerMissingWorkflowModel {
            get {
                return ResourceManager.GetString("ProcessManagerMissingWorkflowModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find a channel with the key {0} in the target model..
        /// </summary>
        internal static string UnableToFindAChannelWithTheKeyInTargetModel {
            get {
                return ResourceManager.GetString("UnableToFindAChannelWithTheKeyInTargetModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find an intermediary that has an input channel with key {0} in the target model..
        /// </summary>
        internal static string UnableToFindAnIntermediaryWithTheKeyInTargetModel {
            get {
                return ResourceManager.GetString("UnableToFindAnIntermediaryWithTheKeyInTargetModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find a messaging object with channel key reference {0} as an input channel in the target model..
        /// </summary>
        internal static string UnableToFindMessagingObjectWithAnInputChannelInTargetModel {
            get {
                return ResourceManager.GetString("UnableToFindMessagingObjectWithAnInputChannelInTargetModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameters definition for process manager &apos;{0}&apos; does not have a node at the path &apos;{1}&apos;..
        /// </summary>
        internal static string UnableToFindNodeInParametersDefinition {
            get {
                return ResourceManager.GetString("UnableToFindNodeInParametersDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The workflow definition for process manager &apos;{0}&apos; does not have a node at the path &apos;{1}&apos;..
        /// </summary>
        internal static string UnableToFindNodeInWorkflowDefinition {
            get {
                return ResourceManager.GetString("UnableToFindNodeInWorkflowDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find the resource definition for {ResourceDefinition}..
        /// </summary>
        internal static string UnableToFindResourceDefinition {
            get {
                return ResourceManager.GetString("UnableToFindResourceDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find the resource template with a resource template type of {0} for the messaging object with the name {1}..
        /// </summary>
        internal static string UnableToFindResourceTemplateForMessagingObject {
            get {
                return ResourceManager.GetString("UnableToFindResourceTemplateForMessagingObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find the resource with the type {0} and scenario step name of {1} in the target model..
        /// </summary>
        internal static string UnableToFindResourceWithTypeInTargetModelForScenarioStepName {
            get {
                return ResourceManager.GetString("UnableToFindResourceWithTypeInTargetModelForScenarioStepName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The workflow channel &apos;{0}&apos; associated with activity &apos;{1}&apos; could not be found in the workflow model..
        /// </summary>
        internal static string UnableToFindWorkflowChannel {
            get {
                return ResourceManager.GetString("UnableToFindWorkflowChannel", resourceCulture);
            }
        }
    }
}
