//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.AzureIntegrationMigration.BizTalk.Convert.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TraceMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TraceMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.AzureIntegrationMigration.BizTalk.Convert.Resources.TraceMessages", typeof(TraceMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Added action {ActionName} for workflow activity container {ContainerName} to workflow definition actions..
        /// </summary>
        internal static string AddedActionForWorkflowActivityContainerToWorkflowDefinition {
            get {
                return ResourceManager.GetString("AddedActionForWorkflowActivityContainerToWorkflowDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Added action {ActionName} for workflow activity {ActivityName} to workflow definition actions..
        /// </summary>
        internal static string AddedActionForWorkflowActivityToWorkflowDefinition {
            get {
                return ResourceManager.GetString("AddedActionForWorkflowActivityToWorkflowDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Added parameter {ParameterName} to logic app parameters definition..
        /// </summary>
        internal static string AddedParameterToLogicAppParameters {
            get {
                return ResourceManager.GetString("AddedParameterToLogicAppParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Added {ActionCount} pre-built actions to workflow activity container {ContainerName}..
        /// </summary>
        internal static string AddedPreBuiltActionsToWorkflowActivityContainer {
            get {
                return ResourceManager.GetString("AddedPreBuiltActionsToWorkflowActivityContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Added pre-built action {ActionName} with resource type {ResourceType} to workflow activity container {ContainerName}..
        /// </summary>
        internal static string AddedPreBuiltActionToWorkflowActivityContainer {
            get {
                return ResourceManager.GetString("AddedPreBuiltActionToWorkflowActivityContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Added workflow channel {ChannelName} to workflow definition triggers..
        /// </summary>
        internal static string AddedWorkflowChannelToWorkflowDefinitionTriggers {
            get {
                return ResourceManager.GetString("AddedWorkflowChannelToWorkflowDefinitionTriggers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Added workflow message {MessageName} to workflow definition actions..
        /// </summary>
        internal static string AddedWorkflowMessageToWorkflowDefinition {
            get {
                return ResourceManager.GetString("AddedWorkflowMessageToWorkflowDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Added workflow parameter {ParameterName} to ARM parameters file..
        /// </summary>
        internal static string AddedWorkflowParameterToArmParameters {
            get {
                return ResourceManager.GetString("AddedWorkflowParameterToArmParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Added workflow parameter {ParameterName} to ARM template..
        /// </summary>
        internal static string AddedWorkflowParameterToArmTemplate {
            get {
                return ResourceManager.GetString("AddedWorkflowParameterToArmTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Added workflow parameter {ParameterName} to workflow ARM resource type..
        /// </summary>
        internal static string AddedWorkflowParameterToResourceParameters {
            get {
                return ResourceManager.GetString("AddedWorkflowParameterToResourceParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Added workflow parameter {ParameterName} to workflow parameters definition..
        /// </summary>
        internal static string AddedWorkflowParameterToWorkflowDefinition {
            get {
                return ResourceManager.GetString("AddedWorkflowParameterToWorkflowDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Added workflow property {PropertyName} to workflow ARM resource type..
        /// </summary>
        internal static string AddedWorkflowPropertyToResource {
            get {
                return ResourceManager.GetString("AddedWorkflowPropertyToResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Added workflow property {PropertyName} to workflow resource properties..
        /// </summary>
        internal static string AddedWorkflowPropertyToResourceProperties {
            get {
                return ResourceManager.GetString("AddedWorkflowPropertyToResourceProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Added workflow variable {VariableName} to ARM template..
        /// </summary>
        internal static string AddedWorkflowVariableToArmTemplate {
            get {
                return ResourceManager.GetString("AddedWorkflowVariableToArmTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Added workflow variable {VariableName} to workflow definition actions..
        /// </summary>
        internal static string AddedWorkflowVariableToWorkflowDefinition {
            get {
                return ResourceManager.GetString("AddedWorkflowVariableToWorkflowDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Binding action {ActionName} to {PreviousActionName}..
        /// </summary>
        internal static string BindingAction {
            get {
                return ResourceManager.GetString("BindingAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Binding actions for process manager {ProcessManagerName}..
        /// </summary>
        internal static string BindingActions {
            get {
                return ResourceManager.GetString("BindingActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding route for scenario {ScenarioName} and resource {ResourceName}.
        /// </summary>
        internal static string BuildRoutingSlipAddRoute {
            get {
                return ResourceManager.GetString("BuildRoutingSlipAddRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Finding messaging objects in the route with input channels {InputChannels}..
        /// </summary>
        internal static string CheckingInputChannels {
            get {
                return ResourceManager.GetString("CheckingInputChannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Converting activity {ActivityName} with type {ActivityType}..
        /// </summary>
        internal static string ConvertingActivity {
            get {
                return ResourceManager.GetString("ConvertingActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Converting activity container {ActivityContainerName} with type {ActivityContainerType}..
        /// </summary>
        internal static string ConvertingActivityContainer {
            get {
                return ResourceManager.GetString("ConvertingActivityContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Copying snippet file from {SourceFilePath} to {DestinationFilePath}..
        /// </summary>
        internal static string CopyingSnippet {
            get {
                return ResourceManager.GetString("CopyingSnippet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying template file from {SourceFilePath} to {DestinationFilePath}..
        /// </summary>
        internal static string CopyingTemplate {
            get {
                return ResourceManager.GetString("CopyingTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating conversion path {ConversionPath}..
        /// </summary>
        internal static string CreatingConversionPath {
            get {
                return ResourceManager.GetString("CreatingConversionPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating generation path {GenerationPath}..
        /// </summary>
        internal static string CreatingGenerationPath {
            get {
                return ResourceManager.GetString("CreatingGenerationPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Finding resource template of type {ResourceTemplateType} for scenario step {ScenarioStepName} within the scope {ResourceScope}..
        /// </summary>
        internal static string FindingResourceTemplateByScenarioStepName {
            get {
                return ResourceManager.GetString("FindingResourceTemplateByScenarioStepName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Found endpoint {EndpointName} in the route with input channel {ChannelName}..
        /// </summary>
        internal static string FoundEndpointAttachedToChannel {
            get {
                return ResourceManager.GetString("FoundEndpointAttachedToChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Found intermediary {IntermediaryName} in the route with input channel {ChannelName}..
        /// </summary>
        internal static string FoundIntermediaryAttachedToChannel {
            get {
                return ResourceManager.GetString("FoundIntermediaryAttachedToChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Found no resource template of type {ResourceTemplateType} for scenario step {ScenarioStepName} within the scope {ResourceScope}..
        /// </summary>
        internal static string FoundNoResourceTemplateByScenarioStepName {
            get {
                return ResourceManager.GetString("FoundNoResourceTemplateByScenarioStepName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Found {ResourceCount} resource templates of type {ResourceTemplateType} for scenario step {ScenarioStepName}, but only expecting to find a single template within the scope {ResourceScope}..
        /// </summary>
        internal static string FoundTooManyResourceTemplatesByScenarioStepName {
            get {
                return ResourceManager.GetString("FoundTooManyResourceTemplatesByScenarioStepName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Generating workflow for process manager {ProcessManagerName}..
        /// </summary>
        internal static string GeneratingWorkflow {
            get {
                return ResourceManager.GetString("GeneratingWorkflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {GeneratorId}: Completed running rule {GeneratorName}..
        /// </summary>
        internal static string GeneratorCompleted {
            get {
                return ResourceManager.GetString("GeneratorCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Channel {ChannelName} is not part of the route, ignoring..
        /// </summary>
        internal static string IgnoringChannel {
            get {
                return ResourceManager.GetString("IgnoringChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Loading snippet {SnippetPath}..
        /// </summary>
        internal static string LoadingSnippet {
            get {
                return ResourceManager.GetString("LoadingSnippet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading template {TemplatePath}..
        /// </summary>
        internal static string LoadingTemplate {
            get {
                return ResourceManager.GetString("LoadingTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: There are no workflows in application {ApplicationName} to be generated..
        /// </summary>
        internal static string NoWorkflowsToGenerate {
            get {
                return ResourceManager.GetString("NoWorkflowsToGenerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Rendering snippet {SnippetPath} using model and workflow object {WorkflowObjectName} of type {WorkflowObjectType}..
        /// </summary>
        internal static string RenderingSnippet {
            get {
                return ResourceManager.GetString("RenderingSnippet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rendering template {TemplatePath} using model..
        /// </summary>
        internal static string RenderingTemplate {
            get {
                return ResourceManager.GetString("RenderingTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: A routing slip has not been generated for the scenario {Scenario} because not all steps have been implemented as template resources..
        /// </summary>
        internal static string RoutingSlipNotGeneratedForScenario {
            get {
                return ResourceManager.GetString("RoutingSlipNotGeneratedForScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {GeneratorId}: Running rule {GeneratorName}..
        /// </summary>
        internal static string RunningGenerator {
            get {
                return ResourceManager.GetString("RunningGenerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Saved workflow to {WorkflowPath} for process manager {ProcessManagerName}..
        /// </summary>
        internal static string SavedWorkflow {
            get {
                return ResourceManager.GetString("SavedWorkflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving artifact {ArtifactPath}..
        /// </summary>
        internal static string SavingArtifact {
            get {
                return ResourceManager.GetString("SavingArtifact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Saving rendered snippet {RenderedSnippetPath}..
        /// </summary>
        internal static string SavingSnippet {
            get {
                return ResourceManager.GetString("SavingSnippet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving rendered template {RenderedTemplatePath}..
        /// </summary>
        internal static string SavingTemplate {
            get {
                return ResourceManager.GetString("SavingTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Selected workflow definition actions container for rule {Rule}..
        /// </summary>
        internal static string SelectedRuleForWorkflowActivityContainer {
            get {
                return ResourceManager.GetString("SelectedRuleForWorkflowActivityContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Skipping the rule {RuleName} as there is no migration target message bus..
        /// </summary>
        internal static string SkippingRuleAsMigrationTargetMessageBusMissing {
            get {
                return ResourceManager.GetString("SkippingRuleAsMigrationTargetMessageBusMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: The target {TargetName} is not supproted by this converter. No work will be performed..
        /// </summary>
        internal static string TargetNotSupportedByConverter {
            get {
                return ResourceManager.GetString("TargetNotSupportedByConverter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Unable to find the resource template with the type {0} and scenario step name of {1} in the target model..
        /// </summary>
        internal static string UnableToFindResourceWithTypeInTargetModelForScenarioStepName {
            get {
                return ResourceManager.GetString("UnableToFindResourceWithTypeInTargetModelForScenarioStepName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Walking the route for scenario {ScenarioName} starting from activating intermediary {IntermediaryName}..
        /// </summary>
        internal static string WalkingOrchestrationRoute {
            get {
                return ResourceManager.GetString("WalkingOrchestrationRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Walking the route for scenario {ScenarioName} starting from activating endpoint {EndpointName}..
        /// </summary>
        internal static string WalkingReceiveRoute {
            get {
                return ResourceManager.GetString("WalkingReceiveRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: Walking the route for scenario {ScenarioName} starting from activating intermediary {IntermediaryName}..
        /// </summary>
        internal static string WalkingSendRoute {
            get {
                return ResourceManager.GetString("WalkingSendRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: No workflow activity container placeholder snippet with type {SnippetResourceType} was found..
        /// </summary>
        internal static string WorkflowActivityContainerPlaceHolderSnippetNotFound {
            get {
                return ResourceManager.GetString("WorkflowActivityContainerPlaceHolderSnippetNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: No workflow activity container snippet with type {SnippetResourceType} was found, using placeholder instead..
        /// </summary>
        internal static string WorkflowActivityContainerSnippetNotFound {
            get {
                return ResourceManager.GetString("WorkflowActivityContainerSnippetNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: No workflow activity placeholder snippet with type {SnippetResourceType} was found..
        /// </summary>
        internal static string WorkflowActivityPlaceHolderSnippetNotFound {
            get {
                return ResourceManager.GetString("WorkflowActivityPlaceHolderSnippetNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: No workflow activity snippet with type {SnippetResourceType} was found, using placeholder instead..
        /// </summary>
        internal static string WorkflowActivitySnippetNotFound {
            get {
                return ResourceManager.GetString("WorkflowActivitySnippetNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: No workflow channel snippets found for process manager {ProcessManagerName}..
        /// </summary>
        internal static string WorkflowChannelSnippetsNotFound {
            get {
                return ResourceManager.GetString("WorkflowChannelSnippetsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: No workflow message placeholder snippet with type {SnippetResourceType} was found..
        /// </summary>
        internal static string WorkflowMessagePlaceHolderSnippetNotFound {
            get {
                return ResourceManager.GetString("WorkflowMessagePlaceHolderSnippetNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: No workflow message snippets found for process manager {ProcessManagerName}..
        /// </summary>
        internal static string WorkflowMessageSnippetsNotFound {
            get {
                return ResourceManager.GetString("WorkflowMessageSnippetsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: No workflow parameter snippets found for process manager {ProcessManagerName}..
        /// </summary>
        internal static string WorkflowParameterSnippetsNotFound {
            get {
                return ResourceManager.GetString("WorkflowParameterSnippetsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: No workflow property snippets found for process manager {ProcessManagerName}..
        /// </summary>
        internal static string WorkflowPropertySnippetsNotFound {
            get {
                return ResourceManager.GetString("WorkflowPropertySnippetsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: No workflow variable placeholder snippet with type {SnippetResourceType} was found..
        /// </summary>
        internal static string WorkflowVariablePlaceHolderSnippetNotFound {
            get {
                return ResourceManager.GetString("WorkflowVariablePlaceHolderSnippetNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RuleId}: No workflow variable snippets found for process manager {ProcessManagerName}..
        /// </summary>
        internal static string WorkflowVariableSnippetsNotFound {
            get {
                return ResourceManager.GetString("WorkflowVariableSnippetsNotFound", resourceCulture);
            }
        }
    }
}
