//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.AzureIntegrationMigration.BizTalk.Convert.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WarningMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WarningMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.AzureIntegrationMigration.BizTalk.Convert.Resources.WarningMessages", typeof(WarningMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no template paths provided to the converter..
        /// </summary>
        internal static string NoTemplatePathsFound {
            get {
                return ResourceManager.GetString("NoTemplatePathsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The process manager {ProcessManagerName} doesn&apos;t have an associated resource template of type {TemplateResourceType}.  Check the resource configuration is correct..
        /// </summary>
        internal static string ProcessManagerResourceTemplateNotFound {
            get {
                return ResourceManager.GetString("ProcessManagerResourceTemplateNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The process manager {ProcessManagerName} doesn&apos;t contain a snippet with resource type {SnippetResourceType}..
        /// </summary>
        internal static string ProcessManagerSnippetNotFound {
            get {
                return ResourceManager.GetString("ProcessManagerSnippetNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The process manager {ProcessManagerName} doesn&apos;t have any snippets associated with it.  Check the resource configuration is correct..
        /// </summary>
        internal static string ProcessManagerSnippetsNotFound {
            get {
                return ResourceManager.GetString("ProcessManagerSnippetsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The resource definition {ResourceDefinition} was not found..
        /// </summary>
        internal static string ResourceDefinitionNotFound {
            get {
                return ResourceManager.GetString("ResourceDefinitionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The resource with the key {Key} was not found in the source model..
        /// </summary>
        internal static string ResourceNotFoundByKey {
            get {
                return ResourceManager.GetString("ResourceNotFoundByKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The resource with the refId {RefId} was not found in the source model..
        /// </summary>
        internal static string ResourceNotFoundByRefId {
            get {
                return ResourceManager.GetString("ResourceNotFoundByRefId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A routing slip has not been generated for the scenario {0} because not all steps have been implemented as template resources..
        /// </summary>
        internal static string RoutingSlipNotGeneratedForScenario {
            get {
                return ResourceManager.GetString("RoutingSlipNotGeneratedForScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The snippet file {SnippetFilePath} was not found in any provided template path..
        /// </summary>
        internal static string SnippetFileNotFound {
            get {
                return ResourceManager.GetString("SnippetFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The template file {TemplateFilePath} was not found in any provided template path..
        /// </summary>
        internal static string TemplateFileNotFound {
            get {
                return ResourceManager.GetString("TemplateFileNotFound", resourceCulture);
            }
        }
    }
}
