//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace Microsoft.AzureIntegrationMigration.BizTalk.Types.Entities.Bindings {
    using System.Xml.Serialization;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
    public partial class BindingInfo {
        
        private string descriptionField;
        
        private System.DateTime timestampField;
        
        private ModuleRef[] moduleRefCollectionField;
        
        private SendPort[] sendPortCollectionField;
        
        private DistributionList[] distributionListCollectionField;
        
        private ReceivePort[] receivePortCollectionField;
        
        private System.Data.DataSet partyCollectionField;
        
        private System.Xml.XmlNode ediGlobalPropertiesField;
        
        private string assemblyField;
        
        private string versionField;
        
        private BindingState bindingStatusField;
        
        private int boundEndpointsField;
        
        private int totalEndpointsField;
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public ModuleRef[] ModuleRefCollection {
            get {
                return this.moduleRefCollectionField;
            }
            set {
                this.moduleRefCollectionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public SendPort[] SendPortCollection {
            get {
                return this.sendPortCollectionField;
            }
            set {
                this.sendPortCollectionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public DistributionList[] DistributionListCollection {
            get {
                return this.distributionListCollectionField;
            }
            set {
                this.distributionListCollectionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public ReceivePort[] ReceivePortCollection {
            get {
                return this.receivePortCollectionField;
            }
            set {
                this.receivePortCollectionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataSet PartyCollection {
            get {
                return this.partyCollectionField;
            }
            set {
                this.partyCollectionField = value;
            }
        }
        
        /// <remarks/>
        public System.Xml.XmlNode EdiGlobalProperties {
            get {
                return this.ediGlobalPropertiesField;
            }
            set {
                this.ediGlobalPropertiesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Assembly {
            get {
                return this.assemblyField;
            }
            set {
                this.assemblyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public BindingState BindingStatus {
            get {
                return this.bindingStatusField;
            }
            set {
                this.bindingStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int BoundEndpoints {
            get {
                return this.boundEndpointsField;
            }
            set {
                this.boundEndpointsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int TotalEndpoints {
            get {
                return this.totalEndpointsField;
            }
            set {
                this.totalEndpointsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ModuleRef : BindingBaseObject {
        
        private ServiceRef[] servicesField;
        
        private Schema[] trackedSchemasField;
        
        private string nameField;
        
        private string versionField;
        
        private string cultureField;
        
        private string publicKeyTokenField;
        
        private string fullNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Service")]
        public ServiceRef[] Services {
            get {
                return this.servicesField;
            }
            set {
                this.servicesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public Schema[] TrackedSchemas {
            get {
                return this.trackedSchemasField;
            }
            set {
                this.trackedSchemasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Culture {
            get {
                return this.cultureField;
            }
            set {
                this.cultureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PublicKeyToken {
            get {
                return this.publicKeyTokenField;
            }
            set {
                this.publicKeyTokenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FullName {
            get {
                return this.fullNameField;
            }
            set {
                this.fullNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ServiceRef : BindingBaseObject {
        
        private ServicePortRef[] portsField;
        
        private RoleRef[] rolesField;
        
        private HostRef hostField;
        
        private string nameField;
        
        private ServiceRefState stateField;
        
        private OrchestrationTrackingTypes trackingOptionField;
        
        private bool analyticsEnabledField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Port")]
        public ServicePortRef[] Ports {
            get {
                return this.portsField;
            }
            set {
                this.portsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Role")]
        public RoleRef[] Roles {
            get {
                return this.rolesField;
            }
            set {
                this.rolesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public HostRef Host {
            get {
                return this.hostField;
            }
            set {
                this.hostField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ServiceRefState State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public OrchestrationTrackingTypes TrackingOption {
            get {
                return this.trackingOptionField;
            }
            set {
                this.trackingOptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool AnalyticsEnabled {
            get {
                return this.analyticsEnabledField;
            }
            set {
                this.analyticsEnabledField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ServicePortRef : BindingBaseObject {
        
        private SendPortRef sendPortRefField;
        
        private DistributionListRef distributionListRefField;
        
        private ReceivePortRef receivePortRefField;
        
        private string nameField;
        
        private int modifierField;
        
        private int bindingOptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public SendPortRef SendPortRef {
            get {
                return this.sendPortRefField;
            }
            set {
                this.sendPortRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public DistributionListRef DistributionListRef {
            get {
                return this.distributionListRefField;
            }
            set {
                this.distributionListRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ReceivePortRef ReceivePortRef {
            get {
                return this.receivePortRefField;
            }
            set {
                this.receivePortRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Modifier {
            get {
                return this.modifierField;
            }
            set {
                this.modifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int BindingOption {
            get {
                return this.bindingOptionField;
            }
            set {
                this.bindingOptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendPortRef {
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendHandlerRef {
        
        private ProtocolType transportTypeField;
        
        private string nameField;
        
        private bool hostTrustedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ProtocolType TransportType {
            get {
                return this.transportTypeField;
            }
            set {
                this.transportTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool HostTrusted {
            get {
                return this.hostTrustedField;
            }
            set {
                this.hostTrustedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProtocolType {
        
        private string nameField;
        
        private int capabilitiesField;
        
        private string configurationClsidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Capabilities {
            get {
                return this.capabilitiesField;
            }
            set {
                this.capabilitiesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ConfigurationClsid {
            get {
                return this.configurationClsidField;
            }
            set {
                this.configurationClsidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Transform {
        
        private string fullNameField;
        
        private string assemblyQualifiedNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FullName {
            get {
                return this.fullNameField;
            }
            set {
                this.fullNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AssemblyQualifiedName {
            get {
                return this.assemblyQualifiedNameField;
            }
            set {
                this.assemblyQualifiedNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReceiveHandlerRef {
        
        private ProtocolType transportTypeField;
        
        private string nameField;
        
        private bool hostTrustedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ProtocolType TransportType {
            get {
                return this.transportTypeField;
            }
            set {
                this.transportTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool HostTrusted {
            get {
                return this.hostTrustedField;
            }
            set {
                this.hostTrustedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CertificateInfo {
        
        private string longNameField;
        
        private string shortNameField;
        
        private CertUsageType usageTypeField;
        
        private string thumbPrintField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string LongName {
            get {
                return this.longNameField;
            }
            set {
                this.longNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ShortName {
            get {
                return this.shortNameField;
            }
            set {
                this.shortNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public CertUsageType UsageType {
            get {
                return this.usageTypeField;
            }
            set {
                this.usageTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ThumbPrint {
            get {
                return this.thumbPrintField;
            }
            set {
                this.thumbPrintField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.FlagsAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum CertUsageType {
        
        /// <remarks/>
        None = 1,
        
        /// <remarks/>
        Encryption = 2,
        
        /// <remarks/>
        Signature = 4,
        
        /// <remarks/>
        Both = 8,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PipelineRef {
        
        private string nameField;
        
        private string fullyQualifiedNameField;
        
        private int typeField;
        
        private PipelineTrackingTypes trackingOptionField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FullyQualifiedName {
            get {
                return this.fullyQualifiedNameField;
            }
            set {
                this.fullyQualifiedNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public PipelineTrackingTypes TrackingOption {
            get {
                return this.trackingOptionField;
            }
            set {
                this.trackingOptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.FlagsAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum PipelineTrackingTypes {
        
        /// <remarks/>
        None = 1,
        
        /// <remarks/>
        ServiceStartEnd = 2,
        
        /// <remarks/>
        MessageSendReceive = 4,
        
        /// <remarks/>
        InboundMessageBody = 8,
        
        /// <remarks/>
        OutboundMessageBody = 16,
        
        /// <remarks/>
        PipelineEvents = 32,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Schema {
        
        private string[] trackedPropertyNamesField;
        
        private string fullNameField;
        
        private string rootNameField;
        
        private string assemblyQualifiedNameField;
        
        private bool alwaysTrackAllPropertiesField;
        
        private string descriptionField;
        
        /// <remarks/>
        public string[] TrackedPropertyNames {
            get {
                return this.trackedPropertyNamesField;
            }
            set {
                this.trackedPropertyNamesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FullName {
            get {
                return this.fullNameField;
            }
            set {
                this.fullNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RootName {
            get {
                return this.rootNameField;
            }
            set {
                this.rootNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AssemblyQualifiedName {
            get {
                return this.assemblyQualifiedNameField;
            }
            set {
                this.assemblyQualifiedNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool AlwaysTrackAllProperties {
            get {
                return this.alwaysTrackAllPropertiesField;
            }
            set {
                this.alwaysTrackAllPropertiesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HostRef {
        
        private string nameField;
        
        private string nTGroupNameField;
        
        private int typeField;
        
        private bool trustedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NTGroupName {
            get {
                return this.nTGroupNameField;
            }
            set {
                this.nTGroupNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Trusted {
            get {
                return this.trustedField;
            }
            set {
                this.trustedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EnlistedPartyMapping {
        
        private SendPortRef sendPortRefField;
        
        private string portTypeNameField;
        
        private string operationNameField;
        
        /// <remarks/>
        public SendPortRef SendPortRef {
            get {
                return this.sendPortRefField;
            }
            set {
                this.sendPortRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PortTypeName {
            get {
                return this.portTypeNameField;
            }
            set {
                this.portTypeNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OperationName {
            get {
                return this.operationNameField;
            }
            set {
                this.operationNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReceivePortRef {
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DistributionListRef {
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SendPort))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TransportInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DistributionList))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ReceivePort))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ReceiveLocation))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EnlistedParty))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RoleRef))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ServicePortRef))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ServiceRef))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ModuleRef))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public abstract partial class BindingBaseObject {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendPort : BindingBaseObject {
        
        private string descriptionField;
        
        private PipelineRef transmitPipelineField;
        
        private string sendPipelineDataField;
        
        private TransportInfo primaryTransportField;
        
        private TransportInfo secondaryTransportField;
        
        private CertificateInfo encryptionCertField;
        
        private PipelineRef receivePipelineField;
        
        private string receivePipelineDataField;
        
        private int trackingField;
        
        private string filterField;
        
        private Transform[] transformsField;
        
        private Transform[] inboundTransformsField;
        
        private bool orderedDeliveryField;
        
        private int priorityField;
        
        private bool stopSendingOnFailureField;
        
        private bool routeFailedMessageField;
        
        private string applicationNameField;
        
        private string nameField;
        
        private bool isStaticField;
        
        private bool isTwoWayField;
        
        private int bindingOptionField;
        
        private bool analyticsEnabledField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public PipelineRef TransmitPipeline {
            get {
                return this.transmitPipelineField;
            }
            set {
                this.transmitPipelineField = value;
            }
        }
        
        /// <remarks/>
        public string SendPipelineData {
            get {
                return this.sendPipelineDataField;
            }
            set {
                this.sendPipelineDataField = value;
            }
        }
        
        /// <remarks/>
        public TransportInfo PrimaryTransport {
            get {
                return this.primaryTransportField;
            }
            set {
                this.primaryTransportField = value;
            }
        }
        
        /// <remarks/>
        public TransportInfo SecondaryTransport {
            get {
                return this.secondaryTransportField;
            }
            set {
                this.secondaryTransportField = value;
            }
        }
        
        /// <remarks/>
        public CertificateInfo EncryptionCert {
            get {
                return this.encryptionCertField;
            }
            set {
                this.encryptionCertField = value;
            }
        }
        
        /// <remarks/>
        public PipelineRef ReceivePipeline {
            get {
                return this.receivePipelineField;
            }
            set {
                this.receivePipelineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ReceivePipelineData {
            get {
                return this.receivePipelineDataField;
            }
            set {
                this.receivePipelineDataField = value;
            }
        }
        
        /// <remarks/>
        public int Tracking {
            get {
                return this.trackingField;
            }
            set {
                this.trackingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Filter {
            get {
                return this.filterField;
            }
            set {
                this.filterField = value;
            }
        }
        
        /// <remarks/>
        public Transform[] Transforms {
            get {
                return this.transformsField;
            }
            set {
                this.transformsField = value;
            }
        }
        
        /// <remarks/>
        public Transform[] InboundTransforms {
            get {
                return this.inboundTransformsField;
            }
            set {
                this.inboundTransformsField = value;
            }
        }
        
        /// <remarks/>
        public bool OrderedDelivery {
            get {
                return this.orderedDeliveryField;
            }
            set {
                this.orderedDeliveryField = value;
            }
        }
        
        /// <remarks/>
        public int Priority {
            get {
                return this.priorityField;
            }
            set {
                this.priorityField = value;
            }
        }
        
        /// <remarks/>
        public bool StopSendingOnFailure {
            get {
                return this.stopSendingOnFailureField;
            }
            set {
                this.stopSendingOnFailureField = value;
            }
        }
        
        /// <remarks/>
        public bool RouteFailedMessage {
            get {
                return this.routeFailedMessageField;
            }
            set {
                this.routeFailedMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ApplicationName {
            get {
                return this.applicationNameField;
            }
            set {
                this.applicationNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool IsStatic {
            get {
                return this.isStaticField;
            }
            set {
                this.isStaticField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool IsTwoWay {
            get {
                return this.isTwoWayField;
            }
            set {
                this.isTwoWayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int BindingOption {
            get {
                return this.bindingOptionField;
            }
            set {
                this.bindingOptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool AnalyticsEnabled {
            get {
                return this.analyticsEnabledField;
            }
            set {
                this.analyticsEnabledField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TransportInfo : BindingBaseObject {
        
        private string addressField;
        
        private ProtocolType transportTypeField;
        
        private string transportTypeDataField;
        
        private int retryCountField;
        
        private int retryIntervalField;
        
        private bool serviceWindowEnabledField;
        
        private System.DateTime fromTimeField;
        
        private System.DateTime toTimeField;
        
        private bool primaryField;
        
        private bool orderedDeliveryField;
        
        private int deliveryNotificationField;
        
        private SendHandlerRef sendHandlerField;
        
        /// <remarks/>
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public ProtocolType TransportType {
            get {
                return this.transportTypeField;
            }
            set {
                this.transportTypeField = value;
            }
        }
        
        /// <remarks/>
        public string TransportTypeData {
            get {
                return this.transportTypeDataField;
            }
            set {
                this.transportTypeDataField = value;
            }
        }
        
        /// <remarks/>
        public int RetryCount {
            get {
                return this.retryCountField;
            }
            set {
                this.retryCountField = value;
            }
        }
        
        /// <remarks/>
        public int RetryInterval {
            get {
                return this.retryIntervalField;
            }
            set {
                this.retryIntervalField = value;
            }
        }
        
        /// <remarks/>
        public bool ServiceWindowEnabled {
            get {
                return this.serviceWindowEnabledField;
            }
            set {
                this.serviceWindowEnabledField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FromTime {
            get {
                return this.fromTimeField;
            }
            set {
                this.fromTimeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ToTime {
            get {
                return this.toTimeField;
            }
            set {
                this.toTimeField = value;
            }
        }
        
        /// <remarks/>
        public bool Primary {
            get {
                return this.primaryField;
            }
            set {
                this.primaryField = value;
            }
        }
        
        /// <remarks/>
        public bool OrderedDelivery {
            get {
                return this.orderedDeliveryField;
            }
            set {
                this.orderedDeliveryField = value;
            }
        }
        
        /// <remarks/>
        public int DeliveryNotification {
            get {
                return this.deliveryNotificationField;
            }
            set {
                this.deliveryNotificationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public SendHandlerRef SendHandler {
            get {
                return this.sendHandlerField;
            }
            set {
                this.sendHandlerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DistributionList : BindingBaseObject {
        
        private SendPortRef[] sendPortsField;
        
        private string filterField;
        
        private string applicationNameField;
        
        private string descriptionField;
        
        private string nameField;
        
        /// <remarks/>
        public SendPortRef[] SendPorts {
            get {
                return this.sendPortsField;
            }
            set {
                this.sendPortsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Filter {
            get {
                return this.filterField;
            }
            set {
                this.filterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ApplicationName {
            get {
                return this.applicationNameField;
            }
            set {
                this.applicationNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReceivePort : BindingBaseObject {
        
        private string descriptionField;
        
        private ReceiveLocation[] receiveLocationsField;
        
        private PipelineRef transmitPipelineField;
        
        private string sendPipelineDataField;
        
        private int authenticationField;
        
        private int trackingField;
        
        private Transform[] transformsField;
        
        private Transform[] outboundTransformsField;
        
        private bool routeFailedMessageField;
        
        private string applicationNameField;
        
        private string nameField;
        
        private bool isTwoWayField;
        
        private int bindingOptionField;
        
        private bool analyticsEnabledField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public ReceiveLocation[] ReceiveLocations {
            get {
                return this.receiveLocationsField;
            }
            set {
                this.receiveLocationsField = value;
            }
        }
        
        /// <remarks/>
        public PipelineRef TransmitPipeline {
            get {
                return this.transmitPipelineField;
            }
            set {
                this.transmitPipelineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SendPipelineData {
            get {
                return this.sendPipelineDataField;
            }
            set {
                this.sendPipelineDataField = value;
            }
        }
        
        /// <remarks/>
        public int Authentication {
            get {
                return this.authenticationField;
            }
            set {
                this.authenticationField = value;
            }
        }
        
        /// <remarks/>
        public int Tracking {
            get {
                return this.trackingField;
            }
            set {
                this.trackingField = value;
            }
        }
        
        /// <remarks/>
        public Transform[] Transforms {
            get {
                return this.transformsField;
            }
            set {
                this.transformsField = value;
            }
        }
        
        /// <remarks/>
        public Transform[] OutboundTransforms {
            get {
                return this.outboundTransformsField;
            }
            set {
                this.outboundTransformsField = value;
            }
        }
        
        /// <remarks/>
        public bool RouteFailedMessage {
            get {
                return this.routeFailedMessageField;
            }
            set {
                this.routeFailedMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ApplicationName {
            get {
                return this.applicationNameField;
            }
            set {
                this.applicationNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool IsTwoWay {
            get {
                return this.isTwoWayField;
            }
            set {
                this.isTwoWayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int BindingOption {
            get {
                return this.bindingOptionField;
            }
            set {
                this.bindingOptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool AnalyticsEnabled {
            get {
                return this.analyticsEnabledField;
            }
            set {
                this.analyticsEnabledField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReceiveLocation : BindingBaseObject {
        
        private string descriptionField;
        
        private string addressField;
        
        private string publicAddressField;
        
        private bool primaryField;
        
        private bool receiveLocationServiceWindowEnabledField;
        
        private System.DateTime receiveLocationFromTimeField;
        
        private System.DateTime receiveLocationToTimeField;
        
        private bool receiveLocationStartDateEnabledField;
        
        private System.DateTime receiveLocationStartDateField;
        
        private bool receiveLocationEndDateEnabledField;
        
        private System.DateTime receiveLocationEndDateField;
        
        private ProtocolType receiveLocationTransportTypeField;
        
        private string receiveLocationTransportTypeDataField;
        
        private PipelineRef receivePipelineField;
        
        private string receivePipelineDataField;
        
        private PipelineRef sendPipelineField;
        
        private string sendPipelineDataField;
        
        private CertificateInfo encryptionCertField;
        
        private bool enableField;
        
        private ReceiveHandlerRef receiveHandlerField;
        
        private RecurrenceType scheduleRecurrenceTypeField;
        
        private System.DateTime scheduleRecurenceFromField;
        
        private int scheduleRecurrenceIntervalField;
        
        private BtsDayOfWeek scheduleDaysOfWeekField;
        
        private Month scheduleMonthsField;
        
        private MonthDay scheduleMonthDaysField;
        
        private BtsDayOfWeek scheduleOrdinalDayOfWeekField;
        
        private OrdinalType scheduleOrdinalTypeField;
        
        private bool scheduleIsOrdinalField;
        
        private bool scheduleLastDayOfMonthField;
        
        private bool scheduleAutoAdjustToDaylightSavingField;
        
        private string scheduleTimeZoneField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PublicAddress {
            get {
                return this.publicAddressField;
            }
            set {
                this.publicAddressField = value;
            }
        }
        
        /// <remarks/>
        public bool Primary {
            get {
                return this.primaryField;
            }
            set {
                this.primaryField = value;
            }
        }
        
        /// <remarks/>
        public bool ReceiveLocationServiceWindowEnabled {
            get {
                return this.receiveLocationServiceWindowEnabledField;
            }
            set {
                this.receiveLocationServiceWindowEnabledField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ReceiveLocationFromTime {
            get {
                return this.receiveLocationFromTimeField;
            }
            set {
                this.receiveLocationFromTimeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ReceiveLocationToTime {
            get {
                return this.receiveLocationToTimeField;
            }
            set {
                this.receiveLocationToTimeField = value;
            }
        }
        
        /// <remarks/>
        public bool ReceiveLocationStartDateEnabled {
            get {
                return this.receiveLocationStartDateEnabledField;
            }
            set {
                this.receiveLocationStartDateEnabledField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ReceiveLocationStartDate {
            get {
                return this.receiveLocationStartDateField;
            }
            set {
                this.receiveLocationStartDateField = value;
            }
        }
        
        /// <remarks/>
        public bool ReceiveLocationEndDateEnabled {
            get {
                return this.receiveLocationEndDateEnabledField;
            }
            set {
                this.receiveLocationEndDateEnabledField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ReceiveLocationEndDate {
            get {
                return this.receiveLocationEndDateField;
            }
            set {
                this.receiveLocationEndDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ProtocolType ReceiveLocationTransportType {
            get {
                return this.receiveLocationTransportTypeField;
            }
            set {
                this.receiveLocationTransportTypeField = value;
            }
        }
        
        /// <remarks/>
        public string ReceiveLocationTransportTypeData {
            get {
                return this.receiveLocationTransportTypeDataField;
            }
            set {
                this.receiveLocationTransportTypeDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public PipelineRef ReceivePipeline {
            get {
                return this.receivePipelineField;
            }
            set {
                this.receivePipelineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ReceivePipelineData {
            get {
                return this.receivePipelineDataField;
            }
            set {
                this.receivePipelineDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public PipelineRef SendPipeline {
            get {
                return this.sendPipelineField;
            }
            set {
                this.sendPipelineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SendPipelineData {
            get {
                return this.sendPipelineDataField;
            }
            set {
                this.sendPipelineDataField = value;
            }
        }
        
        /// <remarks/>
        public CertificateInfo EncryptionCert {
            get {
                return this.encryptionCertField;
            }
            set {
                this.encryptionCertField = value;
            }
        }
        
        /// <remarks/>
        public bool Enable {
            get {
                return this.enableField;
            }
            set {
                this.enableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ReceiveHandlerRef ReceiveHandler {
            get {
                return this.receiveHandlerField;
            }
            set {
                this.receiveHandlerField = value;
            }
        }
        
        /// <remarks/>
        public RecurrenceType ScheduleRecurrenceType {
            get {
                return this.scheduleRecurrenceTypeField;
            }
            set {
                this.scheduleRecurrenceTypeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ScheduleRecurenceFrom {
            get {
                return this.scheduleRecurenceFromField;
            }
            set {
                this.scheduleRecurenceFromField = value;
            }
        }
        
        /// <remarks/>
        public int ScheduleRecurrenceInterval {
            get {
                return this.scheduleRecurrenceIntervalField;
            }
            set {
                this.scheduleRecurrenceIntervalField = value;
            }
        }
        
        /// <remarks/>
        public BtsDayOfWeek ScheduleDaysOfWeek {
            get {
                return this.scheduleDaysOfWeekField;
            }
            set {
                this.scheduleDaysOfWeekField = value;
            }
        }
        
        /// <remarks/>
        public Month ScheduleMonths {
            get {
                return this.scheduleMonthsField;
            }
            set {
                this.scheduleMonthsField = value;
            }
        }
        
        /// <remarks/>
        public MonthDay ScheduleMonthDays {
            get {
                return this.scheduleMonthDaysField;
            }
            set {
                this.scheduleMonthDaysField = value;
            }
        }
        
        /// <remarks/>
        public BtsDayOfWeek ScheduleOrdinalDayOfWeek {
            get {
                return this.scheduleOrdinalDayOfWeekField;
            }
            set {
                this.scheduleOrdinalDayOfWeekField = value;
            }
        }
        
        /// <remarks/>
        public OrdinalType ScheduleOrdinalType {
            get {
                return this.scheduleOrdinalTypeField;
            }
            set {
                this.scheduleOrdinalTypeField = value;
            }
        }
        
        /// <remarks/>
        public bool ScheduleIsOrdinal {
            get {
                return this.scheduleIsOrdinalField;
            }
            set {
                this.scheduleIsOrdinalField = value;
            }
        }
        
        /// <remarks/>
        public bool ScheduleLastDayOfMonth {
            get {
                return this.scheduleLastDayOfMonthField;
            }
            set {
                this.scheduleLastDayOfMonthField = value;
            }
        }
        
        /// <remarks/>
        public bool ScheduleAutoAdjustToDaylightSaving {
            get {
                return this.scheduleAutoAdjustToDaylightSavingField;
            }
            set {
                this.scheduleAutoAdjustToDaylightSavingField = value;
            }
        }
        
        /// <remarks/>
        public string ScheduleTimeZone {
            get {
                return this.scheduleTimeZoneField;
            }
            set {
                this.scheduleTimeZoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.FlagsAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum RecurrenceType {
        
        /// <remarks/>
        None = 1,
        
        /// <remarks/>
        Day = 2,
        
        /// <remarks/>
        Week = 4,
        
        /// <remarks/>
        Month = 8,
    }
    
    /// <remarks/>
    [System.FlagsAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum BtsDayOfWeek {
        
        /// <remarks/>
        None = 1,
        
        /// <remarks/>
        Monday = 2,
        
        /// <remarks/>
        Tuesday = 4,
        
        /// <remarks/>
        Wednesday = 8,
        
        /// <remarks/>
        Thursday = 16,
        
        /// <remarks/>
        Friday = 32,
        
        /// <remarks/>
        Saturday = 64,
        
        /// <remarks/>
        Sunday = 128,
    }
    
    /// <remarks/>
    [System.FlagsAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum Month {
        
        /// <remarks/>
        None = 1,
        
        /// <remarks/>
        January = 2,
        
        /// <remarks/>
        Feburary = 4,
        
        /// <remarks/>
        March = 8,
        
        /// <remarks/>
        April = 16,
        
        /// <remarks/>
        May = 32,
        
        /// <remarks/>
        June = 64,
        
        /// <remarks/>
        July = 128,
        
        /// <remarks/>
        August = 256,
        
        /// <remarks/>
        September = 512,
        
        /// <remarks/>
        October = 1024,
        
        /// <remarks/>
        November = 2048,
        
        /// <remarks/>
        December = 4096,
    }
    
    /// <remarks/>
    [System.FlagsAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum MonthDay : long {
        
        /// <remarks/>
        None = 1,
        
        /// <remarks/>
        Day01 = 2,
        
        /// <remarks/>
        Day02 = 4,
        
        /// <remarks/>
        Day03 = 8,
        
        /// <remarks/>
        Day04 = 16,
        
        /// <remarks/>
        Day05 = 32,
        
        /// <remarks/>
        Day06 = 64,
        
        /// <remarks/>
        Day07 = 128,
        
        /// <remarks/>
        Day08 = 256,
        
        /// <remarks/>
        Day09 = 512,
        
        /// <remarks/>
        Day10 = 1024,
        
        /// <remarks/>
        Day11 = 2048,
        
        /// <remarks/>
        Day12 = 4096,
        
        /// <remarks/>
        Day13 = 8192,
        
        /// <remarks/>
        Day14 = 16384,
        
        /// <remarks/>
        Day15 = 32768,
        
        /// <remarks/>
        Day16 = 65536,
        
        /// <remarks/>
        Day17 = 131072,
        
        /// <remarks/>
        Day18 = 262144,
        
        /// <remarks/>
        Day19 = 524288,
        
        /// <remarks/>
        Day20 = 1048576,
        
        /// <remarks/>
        Day21 = 2097152,
        
        /// <remarks/>
        Day22 = 4194304,
        
        /// <remarks/>
        Day23 = 8388608,
        
        /// <remarks/>
        Day24 = 16777216,
        
        /// <remarks/>
        Day25 = 33554432,
        
        /// <remarks/>
        Day26 = 67108864,
        
        /// <remarks/>
        Day27 = 134217728,
        
        /// <remarks/>
        Day28 = 268435456,
        
        /// <remarks/>
        Day29 = 536870912,
        
        /// <remarks/>
        Day30 = 1073741824,
        
        /// <remarks/>
        Day31 = 2147483648,
    }
    
    /// <remarks/>
    [System.FlagsAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum OrdinalType {
        
        /// <remarks/>
        None = 1,
        
        /// <remarks/>
        First = 2,
        
        /// <remarks/>
        Second = 4,
        
        /// <remarks/>
        Third = 8,
        
        /// <remarks/>
        Fourth = 16,
        
        /// <remarks/>
        SecondLast = 32,
        
        /// <remarks/>
        Last = 64,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EnlistedParty : BindingBaseObject {
        
        private EnlistedPartyMapping[] mappingsField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Mapping")]
        public EnlistedPartyMapping[] Mappings {
            get {
                return this.mappingsField;
            }
            set {
                this.mappingsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RoleRef : BindingBaseObject {
        
        private EnlistedParty[] enlistedPartiesField;
        
        private string nameField;
        
        private string roleLinkTypeNameField;
        
        private RoleRefType roleTypeField;
        
        /// <remarks/>
        public EnlistedParty[] EnlistedParties {
            get {
                return this.enlistedPartiesField;
            }
            set {
                this.enlistedPartiesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RoleLinkTypeName {
            get {
                return this.roleLinkTypeNameField;
            }
            set {
                this.roleLinkTypeNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public RoleRefType RoleType {
            get {
                return this.roleTypeField;
            }
            set {
                this.roleTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum RoleRefType {
        
        /// <remarks/>
        Unknown,
        
        /// <remarks/>
        Implements,
        
        /// <remarks/>
        Uses,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum ServiceRefState {
        
        /// <remarks/>
        Default,
        
        /// <remarks/>
        Unenlisted,
        
        /// <remarks/>
        Enlisted,
        
        /// <remarks/>
        Started,
    }
    
    /// <remarks/>
    [System.FlagsAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum OrchestrationTrackingTypes {
        
        /// <remarks/>
        None = 1,
        
        /// <remarks/>
        ServiceStartEnd = 2,
        
        /// <remarks/>
        MessageSendReceive = 4,
        
        /// <remarks/>
        InboundMessageBody = 8,
        
        /// <remarks/>
        OutboundMessageBody = 16,
        
        /// <remarks/>
        OrchestrationEvents = 32,
        
        /// <remarks/>
        TrackPropertiesForIncomingMessages = 64,
        
        /// <remarks/>
        TrackPropertiesForOutgoingMessages = 128,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum BindingState {
        
        /// <remarks/>
        Unknown,
        
        /// <remarks/>
        NoBindings,
        
        /// <remarks/>
        Unbound,
        
        /// <remarks/>
        PartiallyBound,
        
        /// <remarks/>
        FullyBound,
    }
}
