// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.AzureIntegrationMigration.BizTalk.Cli.Tests.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InformationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InformationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.AzureIntegrationMigration.BizTalk.Cli.Tests.Resources.InformationMessag" +
                            "es", typeof(InformationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BizTalk Analysis complete.
        /// </summary>
        internal static string AnalysisComplete {
            get {
                return ResourceManager.GetString("AnalysisComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BizTalk Analysis started.
        /// </summary>
        internal static string AnalysisStarted {
            get {
                return ResourceManager.GetString("AnalysisStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BizTalk Discovering complete.
        /// </summary>
        internal static string DiscoveringComplete {
            get {
                return ResourceManager.GetString("DiscoveringComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BizTalk Discovering started.
        /// </summary>
        internal static string DiscoveringStarted {
            get {
                return ResourceManager.GetString("DiscoveringStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BizTalk Parsing complete.
        /// </summary>
        internal static string ParsingComplete {
            get {
                return ResourceManager.GetString("ParsingComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BizTalk Parsing started.
        /// </summary>
        internal static string ParsingStarted {
            get {
                return ResourceManager.GetString("ParsingStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BizTalk Reporting complete.
        /// </summary>
        internal static string ReportingComplete {
            get {
                return ResourceManager.GetString("ReportingComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BizTalk Reporting started .
        /// </summary>
        internal static string ReportingStarting {
            get {
                return ResourceManager.GetString("ReportingStarting", resourceCulture);
            }
        }
    }
}
