//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.AzureIntegrationMigration.BizTalk.Parse.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceItemProperties {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceItemProperties() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.AzureIntegrationMigration.BizTalk.Parse.Resources.ResourceItemPropertie" +
                            "s", typeof(ResourceItemProperties).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Envelope Body XPath.
        /// </summary>
        internal static string BodyXPathProperty {
            get {
                return ResourceManager.GetString("BodyXPathProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Type.
        /// </summary>
        internal static string ContextPropertyDataTypeProperty {
            get {
                return ResourceManager.GetString("ContextPropertyDataTypeProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .Net Type Name.
        /// </summary>
        internal static string DotnetTypeNameProperty {
            get {
                return ResourceManager.GetString("DotnetTypeNameProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Duplicate).
        /// </summary>
        internal static string Duplicate {
            get {
                return ResourceManager.GetString("Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dynamic.
        /// </summary>
        internal static string DynamicSendPortType {
            get {
                return ResourceManager.GetString("DynamicSendPortType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Envelope Schema.
        /// </summary>
        internal static string IsEnvelopeProperty {
            get {
                return ResourceManager.GetString("IsEnvelopeProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module Name.
        /// </summary>
        internal static string ModuleNameProperty {
            get {
                return ResourceManager.GetString("ModuleNameProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of root nodes.
        /// </summary>
        internal static string NumberOfRootNodesProperty {
            get {
                return ResourceManager.GetString("NumberOfRootNodesProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One-Way.
        /// </summary>
        internal static string PortDirectionOneWay {
            get {
                return ResourceManager.GetString("PortDirectionOneWay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direction.
        /// </summary>
        internal static string PortDirectionProperty {
            get {
                return ResourceManager.GetString("PortDirectionProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two-Way.
        /// </summary>
        internal static string PortDirectionTwoWay {
            get {
                return ResourceManager.GetString("PortDirectionTwoWay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transport Type.
        /// </summary>
        internal static string PortTransportTypeProperty {
            get {
                return ResourceManager.GetString("PortTransportTypeProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string ReceiveLocationAddressProperty {
            get {
                return ResourceManager.GetString("ReceiveLocationAddressProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root Node Name.
        /// </summary>
        internal static string RootNodeNameProperty {
            get {
                return ResourceManager.GetString("RootNodeNameProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Address.
        /// </summary>
        internal static string SendPortPrimaryAddressProperty {
            get {
                return ResourceManager.GetString("SendPortPrimaryAddressProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Transport Type.
        /// </summary>
        internal static string SendPortPrimaryTransportTypeProperty {
            get {
                return ResourceManager.GetString("SendPortPrimaryTransportTypeProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary Address.
        /// </summary>
        internal static string SendPortSecondaryAddressProperty {
            get {
                return ResourceManager.GetString("SendPortSecondaryAddressProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary Transport Type.
        /// </summary>
        internal static string SendPortSecondaryTransportTypeProperty {
            get {
                return ResourceManager.GetString("SendPortSecondaryTransportTypeProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Port Type.
        /// </summary>
        internal static string SendPortTypeProperty {
            get {
                return ResourceManager.GetString("SendPortTypeProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Static.
        /// </summary>
        internal static string StaticSendPortType {
            get {
                return ResourceManager.GetString("StaticSendPortType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML Namespace.
        /// </summary>
        internal static string XmlNamespaceProperty {
            get {
                return ResourceManager.GetString("XmlNamespaceProperty", resourceCulture);
            }
        }
    }
}
