// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.AzureIntegrationMigration.BizTalk.Parse.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TraceMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TraceMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.AzureIntegrationMigration.BizTalk.Parse.Resources.TraceMessages", typeof(TraceMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed running the parser {ParserName}..
        /// </summary>
        internal static string CompletedParser {
            get {
                return ResourceManager.GetString("CompletedParser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsed the BizTalk orchestration: {OrchestrationName}..
        /// </summary>
        internal static string ParsedBizTalkOrchestration {
            get {
                return ResourceManager.GetString("ParsedBizTalkOrchestration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsed the BizTalk pipeline: {PipelineName}..
        /// </summary>
        internal static string ParsedBizTalkPipeline {
            get {
                return ResourceManager.GetString("ParsedBizTalkPipeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsed the filter expression on the BizTalk send port: {SendPortName}..
        /// </summary>
        internal static string ParsedBizTalkSendPortFilterExpression {
            get {
                return ResourceManager.GetString("ParsedBizTalkSendPortFilterExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsed the send port data in the BizTalk pipeline: {SendPortName}..
        /// </summary>
        internal static string ParsedBizTalkSendPortPipelineData {
            get {
                return ResourceManager.GetString("ParsedBizTalkSendPortPipelineData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsed the BizTalk application with the name: {ApplicationName}..
        /// </summary>
        internal static string ParsedTheBizTalkApplicationWithName {
            get {
                return ResourceManager.GetString("ParsedTheBizTalkApplicationWithName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsed the BizTalk context property: {PropertyName} in the BizTalk schema {SchemaName}..
        /// </summary>
        internal static string ParsedTheBizTalkContextPropertyInSchema {
            get {
                return ResourceManager.GetString("ParsedTheBizTalkContextPropertyInSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing the BizTalk application definition file: {ResourceContainerKey}..
        /// </summary>
        internal static string ParsingBizTalkApplicationDefinitionFileFromResourceContainer {
            get {
                return ResourceManager.GetString("ParsingBizTalkApplicationDefinitionFileFromResourceContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing the BizTalk application from: {ResourceContainerKey}..
        /// </summary>
        internal static string ParsingBizTalkApplicationFromResourceContainer {
            get {
                return ResourceManager.GetString("ParsingBizTalkApplicationFromResourceContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing the BizTalk binding file: {ResourceContainerKey}..
        /// </summary>
        internal static string ParsingBizTalkBindingFileFromResourceContainer {
            get {
                return ResourceManager.GetString("ParsingBizTalkBindingFileFromResourceContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing the BizTalk document schema &apos;{SchemaName}&apos;..
        /// </summary>
        internal static string ParsingBizTalkDocumentSchema {
            get {
                return ResourceManager.GetString("ParsingBizTalkDocumentSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing the BizTalk orchestrations in the application: {ApplicationName}..
        /// </summary>
        internal static string ParsingBizTalkOrchestrationsInApplication {
            get {
                return ResourceManager.GetString("ParsingBizTalkOrchestrationsInApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing the BizTalk pipelines in the application: {ApplicationName}..
        /// </summary>
        internal static string ParsingBizTalkPipelinesInApplication {
            get {
                return ResourceManager.GetString("ParsingBizTalkPipelinesInApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing the BizTalk property schema: {SchemaName}..
        /// </summary>
        internal static string ParsingBizTalkPropertySchema {
            get {
                return ResourceManager.GetString("ParsingBizTalkPropertySchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing the Pipeline data in the BizTalk receive location: {ReceiveLocationName}..
        /// </summary>
        internal static string ParsingBizTalkReceiveLocationPipelineData {
            get {
                return ResourceManager.GetString("ParsingBizTalkReceiveLocationPipelineData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing the BizTalk receive port: {ReceivePortName}..
        /// </summary>
        internal static string ParsingBizTalkReceivePort {
            get {
                return ResourceManager.GetString("ParsingBizTalkReceivePort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing the BizTalk receive port collections in the application: {ApplicationName}..
        /// </summary>
        internal static string ParsingBizTalkReceivePortCollectionInApplication {
            get {
                return ResourceManager.GetString("ParsingBizTalkReceivePortCollectionInApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing the BizTalk schemas in the application: {ApplicationName}..
        /// </summary>
        internal static string ParsingBizTalkSchemasInApplication {
            get {
                return ResourceManager.GetString("ParsingBizTalkSchemasInApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing the BizTalk send pipeline custom configuration for the receive port: {ReceivePortName}..
        /// </summary>
        internal static string ParsingBizTalkSendPipelineCustomConfigurationForReceivePort {
            get {
                return ResourceManager.GetString("ParsingBizTalkSendPipelineCustomConfigurationForReceivePort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing the BizTalk send pipeline data for the application: {ApplicationName}..
        /// </summary>
        internal static string ParsingBizTalkSendPipelineDataInApplication {
            get {
                return ResourceManager.GetString("ParsingBizTalkSendPipelineDataInApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing the BizTalk send port filters in the application: {ApplicationName}..
        /// </summary>
        internal static string ParsingBizTalkSendPortFiltersInApplication {
            get {
                return ResourceManager.GetString("ParsingBizTalkSendPortFiltersInApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing the filters on the BizTalk send ports for the application: {ApplicationName}..
        /// </summary>
        internal static string ParsingBizTalkSendPortGroupFilterForApplication {
            get {
                return ResourceManager.GetString("ParsingBizTalkSendPortGroupFilterForApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing the filters on the BizTalk send ports for the distribution list: {DistributionListName}..
        /// </summary>
        internal static string ParsingBizTalkSendPortGroupFilterForDistributionList {
            get {
                return ResourceManager.GetString("ParsingBizTalkSendPortGroupFilterForDistributionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing the send port data in the BizTalk pipeline: {SendPortName}..
        /// </summary>
        internal static string ParsingBizTalkSendPortPipelineData {
            get {
                return ResourceManager.GetString("ParsingBizTalkSendPortPipelineData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing the BizTalk send pipeline data for the send port: {SendPortName}..
        /// </summary>
        internal static string ParsingBizTalkSendPortPipelineDataForSendPort {
            get {
                return ResourceManager.GetString("ParsingBizTalkSendPortPipelineDataForSendPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing the BizTalk message type definition &apos;{MessageType}&apos;..
        /// </summary>
        internal static string ParsingMessageTypeDefinition {
            get {
                return ResourceManager.GetString("ParsingMessageTypeDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {ParserName}: Created resource &apos;{Key}&apos; Name &apos;{Name}&apos; Type &apos;{Type}&apos; in the resource &apos;{ParentKey}&apos;..
        /// </summary>
        internal static string ResourceCreated {
            get {
                return ResourceManager.GetString("ResourceCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running the parser {ParserName}..
        /// </summary>
        internal static string RunningParser {
            get {
                return ResourceManager.GetString("RunningParser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipping parsing in the {ParserName} as the source model is missing..
        /// </summary>
        internal static string SkippingParserAsTheSourceModelIsMissing {
            get {
                return ResourceManager.GetString("SkippingParserAsTheSourceModelIsMissing", resourceCulture);
            }
        }
    }
}
