//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.AzureIntegrationMigration.BizTalk.Report.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TraceMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TraceMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.AzureIntegrationMigration.BizTalk.Report.Resources.TraceMessages", typeof(TraceMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding application {ApplicationName} to menu..
        /// </summary>
        internal static string ApplicationMenuBuildingItem {
            get {
                return ResourceManager.GetString("ApplicationMenuBuildingItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building menu items for each application....
        /// </summary>
        internal static string ApplicationMenuBuildingList {
            get {
                return ResourceManager.GetString("ApplicationMenuBuildingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding application {ApplicationName} to the report..
        /// </summary>
        internal static string ApplicationSectionAddingItem {
            get {
                return ResourceManager.GetString("ApplicationSectionAddingItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building the application section..
        /// </summary>
        internal static string ApplicationSectionBuildingSection {
            get {
                return ResourceManager.GetString("ApplicationSectionBuildingSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading HTML template from resource file..
        /// </summary>
        internal static string LoadingHtmlTemplate {
            get {
                return ResourceManager.GetString("LoadingHtmlTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Constructing..
        /// </summary>
        internal static string ReporterConstruct {
            get {
                return ResourceManager.GetString("ReporterConstruct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding resource {ResourceName} of type {ResourceType} to the report..
        /// </summary>
        internal static string ResourceAddingItem {
            get {
                return ResourceManager.GetString("ResourceAddingItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding resource container {ResourceContainerName} of type {ResourceType} to the report..
        /// </summary>
        internal static string ResourceContainerAddingItem {
            get {
                return ResourceManager.GetString("ResourceContainerAddingItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building the resource container section..
        /// </summary>
        internal static string ResourceContainerBuildingSection {
            get {
                return ResourceManager.GetString("ResourceContainerBuildingSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding resource definition {ResourceDefinitionName} of type {ResourceType} to the report..
        /// </summary>
        internal static string ResourceDefinitionAddingItem {
            get {
                return ResourceManager.GetString("ResourceDefinitionAddingItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing report to file {ReportFilePath}..
        /// </summary>
        internal static string WritingReportToFile {
            get {
                return ResourceManager.GetString("WritingReportToFile", resourceCulture);
            }
        }
    }
}
