// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.AzureIntegrationMigration.BizTalk.StageRunners.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.AzureIntegrationMigration.BizTalk.StageRunners.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An application model is expected by this stage runner..
        /// </summary>
        internal static string ApplicationModelExpected {
            get {
                return ResourceManager.GetString("ApplicationModelExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application model {0} is not supported by this stage runner..
        /// </summary>
        internal static string ApplicationModelNotExpectedModelType {
            get {
                return ResourceManager.GetString("ApplicationModelNotExpectedModelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected arguments {ArgName} was not found, aborting run..
        /// </summary>
        internal static string ArgumentsNotFound {
            get {
                return ResourceManager.GetString("ArgumentsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to validate supplied arguments, aborting run..
        /// </summary>
        internal static string ArgumentsValidationFailed {
            get {
                return ResourceManager.GetString("ArgumentsValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSI directory {MsiDirectory} does not exist..
        /// </summary>
        internal static string MsiDirectoryDoesNotExist {
            get {
                return ResourceManager.GetString("MsiDirectoryDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSI file {MsiFile} does not exist..
        /// </summary>
        internal static string MsiFileDoesNotExist {
            get {
                return ResourceManager.GetString("MsiFileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No MSI file(s) or directory was specified, nothing to do..
        /// </summary>
        internal static string NoMsiFilesOrDirectorySpecified {
            get {
                return ResourceManager.GetString("NoMsiFilesOrDirectorySpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin {0} failed with errors.
        ///{1}.
        /// </summary>
        internal static string PluginFailedWithErrors {
            get {
                return ResourceManager.GetString("PluginFailedWithErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template configuration directory {TemplateConfigDirectory} does not exist..
        /// </summary>
        internal static string TemplateConfigDirectoryDoesNotExist {
            get {
                return ResourceManager.GetString("TemplateConfigDirectoryDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template directory {TemplateDirectory} does not exist..
        /// </summary>
        internal static string TemplateDirectoryDoesNotExist {
            get {
                return ResourceManager.GetString("TemplateDirectoryDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpack directory {UnpackDirectory} does not exist..
        /// </summary>
        internal static string UnpackDirectoryDoesNotExist {
            get {
                return ResourceManager.GetString("UnpackDirectoryDoesNotExist", resourceCulture);
            }
        }
    }
}
