// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.AzureIntegrationMigration.BizTalk.StageRunners.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TraceMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TraceMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.AzureIntegrationMigration.BizTalk.StageRunners.Resources.TraceMessages", typeof(TraceMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating required output directories for report file path {ReportFilePath}..
        /// </summary>
        internal static string CreatingDirectoriesForReportFilePath {
            get {
                return ResourceManager.GetString("CreatingDirectoriesForReportFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running {GeneratorRuleCount} generator rules for the dependency artifact generator..
        /// </summary>
        internal static string RunningArtifactGeneratorConverter {
            get {
                return ResourceManager.GetString("RunningArtifactGeneratorConverter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running {ConversionRuleCount} dependency rules for the conversion analyzer..
        /// </summary>
        internal static string RunningConversionRulesAnalyzer {
            get {
                return ResourceManager.GetString("RunningConversionRulesAnalyzer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running {DependencyRuleCount} dependency rules for the dependency analyzer..
        /// </summary>
        internal static string RunningDependencyRulesAnalyzer {
            get {
                return ResourceManager.GetString("RunningDependencyRulesAnalyzer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running {InitializerCount} initializer analyzers..
        /// </summary>
        internal static string RunningInitializerAnalyzers {
            get {
                return ResourceManager.GetString("RunningInitializerAnalyzers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running model provider..
        /// </summary>
        internal static string RunningModelProvider {
            get {
                return ResourceManager.GetString("RunningModelProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running {OrchestrationParserCount} parsers for orchestrations..
        /// </summary>
        internal static string RunningOrchestrationParsers {
            get {
                return ResourceManager.GetString("RunningOrchestrationParsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running plugin {PluginName}..
        /// </summary>
        internal static string RunningPlugin {
            get {
                return ResourceManager.GetString("RunningPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running resource generator to populate resources in target model from config..
        /// </summary>
        internal static string RunningResourceGeneratorAnalyzer {
            get {
                return ResourceManager.GetString("RunningResourceGeneratorAnalyzer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running template renderer to parse template files referenced in the target model..
        /// </summary>
        internal static string RunningTemplateRendererConverter {
            get {
                return ResourceManager.GetString("RunningTemplateRendererConverter", resourceCulture);
            }
        }
    }
}
